import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";

const component = readFileSync("src/components/admin/GoldenLessonPackageBuilder.tsx", "utf8");
const route = readFileSync("src/routes/_authenticated/admin.import.tsx", "utf8");

test("Golden Lesson builder is mounted in the official import center", () => {
  assert.match(route, /GoldenLessonPackageBuilder/);
  assert.match(route, /<GoldenLessonPackageBuilder\s*\/>/);
});

test("builder hashes files locally and never calls a server mutation", () => {
  assert.match(component, /crypto\.subtle\.digest\("SHA-256"/);
  assert.doesNotMatch(component, /useServerFn|\.rpc\(|\.insert\(|\.update\(|\.upsert\(|\.delete\(/);
  assert.match(component, /الكتابات المنفذة: \{validation\.writesPerformed\}/);
});

test("production, answer and READY guards are generated by the contract", () => {
  assert.match(component, /productionApply: false/);
  assert.match(component, /publicPayloadContainsAnswers: false/);
  assert.match(component, /answersCompanionSha256/);
  assert.match(component, /initialStatus: "DRAFT"/);
  assert.match(component, /allowDirectReady: false/);
  assert.match(component, /htmlNetworkAccess: "NONE"/);
});

test("manifest download stays gated on successful validation", () => {
  assert.match(component, /disabled=\{!validation\?\.valid\}/);
  assert.match(component, /\.server-only\.json/);
  assert.match(component, /MAX_FILE_BYTES = 5 \* 1024 \* 1024/);
});

test("mobile-first controls meet the 44px target", () => {
  const controls = component.match(/min-h-\[44px\]/g) ?? [];
  assert.ok(controls.length >= 6, `expected at least 6 accessible controls, found ${controls.length}`);
  assert.match(component, /grid-cols-1/);
  assert.match(component, /dir="rtl"/);
});
