import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";

const component = readFileSync("src/components/admin/GoldenLessonPackageBuilder.tsx", "utf8");
const route = readFileSync("src/routes/_authenticated/admin.import.tsx", "utf8");

test("Golden Lesson builder is mounted in the official import center", () => {
  assert.match(route, /GoldenLessonPackageBuilder/);
  assert.match(route, /<GoldenLessonPackageBuilder\s*\/>/);
});

test("builder hashes files locally and never calls a server mutation", () => {
  assert.match(component, /crypto\.subtle\.digest\("SHA-256"/);
  assert.doesNotMatch(component, /useServerFn|\.rpc\(|\.insert\(|\.update\(|\.upsert\(|\.delete\(/);
  assert.match(component, /الكتابات المنفذة: \{validation\.writesPerformed\}/);
});

test("production, answer and READY guards are generated by the contract", () => {
  assert.match(component, /productionApply: false/);
  assert.match(component, /publicPayloadContainsAnswers: false/);
  assert.match(component, /answersCompanionSha256/);
  assert.match(component, /initialStatus: "DRAFT"/);
  assert.match(component, /allowDirectReady: false/);
  assert.match(component, /htmlNetworkAccess: "NONE"/);
});

test("manifest download stays gated on successful validation", () => {
  assert.match(component, /disabled=\{!validation\?\.valid\}/);
  assert.match(component, /\.server-only\.json/);
  assert.match(component, /MAX_FILE_BYTES = 5 \* 1024 \* 1024/);
});

test("mobile-first controls meet the 44px target", () => {
  const controls = component.match(/min-h-\[44px\]/g) ?? [];
  assert.ok(controls.length >= 6, `expected at least 6 accessible controls, found ${controls.length}`);
  assert.match(component, /grid-cols-1/);
  assert.match(component, /dir="rtl"/);
});

test("profile selection is explicit and never defaults to Quran", () => {
  assert.match(component, /useState\(""\)/);
  assert.match(component, /اختر نوع الدرس أولًا/);
  assert.match(component, /handleProfileChange/);
  assert.match(component, /window\.confirm/);
  assert.doesNotMatch(component, /useState\(GOLDEN_QURAN_V1\.id\)/);
});

test("capability inputs use Arabic pickers and strict per-file contracts", () => {
  assert.match(component, /GOLDEN_ARTIFACT_FILE_CONTRACTS/);
  assert.match(component, /validateGoldenLessonArtifactBytes/);
  assert.match(component, /اختيار ملف/);
  assert.match(component, /لم يتم اختيار ملف/);
  assert.match(component, /تم التحقق من الملف/);
  assert.match(component, /لرفع تجربة معملية اختر نوع الدرس «الكيمياء»/);
  assert.doesNotMatch(component, /accept="\.json,\.html,\.zip"/);
});
