import type { QbImportCode, ImportStage } from "../../../src/lib/question-bank/import/validation-codes.ts";

export type FailureCoverageMapping = {
  code: QbImportCode;
  expected_stage: ImportStage;
  source_module: string;
  test_file: string;
  test_name: string;
  fixture_builder: string;
};

export const FAILURE_COVERAGE_MANIFEST: Record<QbImportCode, FailureCoverageMapping> = {
  FILE_TYPE_UNSUPPORTED: {
    code: "FILE_TYPE_UNSUPPORTED",
    expected_stage: "PREFLIGHT_RAW",
    source_module: "zip-preflight",
    test_file: "qb02-binary-security.test.ts",
    test_name: "ZIP structural preflight: non-zip signature",
    fixture_builder: "buildTruncatedZipBytes",
  },
  FILE_TOO_LARGE: {
    code: "FILE_TOO_LARGE",
    expected_stage: "PREFLIGHT_RAW",
    source_module: "zip-preflight",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "5 MiB boundary",
    fixture_builder: "buildMinimalValidXlsx",
  },
  ZIP_BOMB_SUSPECTED: {
    code: "ZIP_BOMB_SUSPECTED",
    expected_stage: "PREFLIGHT_ZIP",
    source_module: "zip-preflight",
    test_file: "qb02-binary-security.test.ts",
    test_name: "ZIP structural preflight: compression ratio overflow",
    fixture_builder: "buildZipWithCompressionRatioOverflow",
  },
  ZIP_ENTRY_LIMIT: {
    code: "ZIP_ENTRY_LIMIT",
    expected_stage: "PREFLIGHT_ZIP",
    source_module: "zip-preflight",
    test_file: "qb02-binary-security.test.ts",
    test_name: "ZIP structural preflight: excessive entries",
    fixture_builder: "buildZipWithExcessiveEntries",
  },
  ZIP_TOTAL_SIZE_LIMIT: {
    code: "ZIP_TOTAL_SIZE_LIMIT",
    expected_stage: "PREFLIGHT_ZIP",
    source_module: "zip-preflight",
    test_file: "qb02-binary-security.test.ts",
    test_name: "ZIP structural preflight: total size overflow",
    fixture_builder: "preflightZipBytes",
  },
  ZIP_DECLARED_SIZE_LIMIT: {
    code: "ZIP_DECLARED_SIZE_LIMIT",
    expected_stage: "PREFLIGHT_ZIP",
    source_module: "zip-preflight",
    test_file: "qb02-binary-security.test.ts",
    test_name: "ZIP structural preflight: single entry declared size limit",
    fixture_builder: "buildZipWithDeclaredSizeOverflow",
  },
  ZIP_DUPLICATE_ENTRY: {
    code: "ZIP_DUPLICATE_ENTRY",
    expected_stage: "PREFLIGHT_ZIP",
    source_module: "zip-preflight",
    test_file: "qb02-binary-security.test.ts",
    test_name: "ZIP structural preflight: duplicate entry name",
    fixture_builder: "buildZipWithDuplicateEntry",
  },
  ZIP_MALFORMED_CENTRAL_DIRECTORY: {
    code: "ZIP_MALFORMED_CENTRAL_DIRECTORY",
    expected_stage: "PREFLIGHT_ZIP",
    source_module: "zip-preflight",
    test_file: "qb02-binary-security.test.ts",
    test_name: "ZIP structural preflight: malformed central directory",
    fixture_builder: "buildMalformedCentralDirectoryZip",
  },
  ZIP_MISSING_EOCD: {
    code: "ZIP_MISSING_EOCD",
    expected_stage: "PREFLIGHT_ZIP",
    source_module: "zip-preflight",
    test_file: "qb02-binary-security.test.ts",
    test_name: "ZIP structural preflight: missing EOCD signature",
    fixture_builder: "buildTruncatedZipBytes",
  },
  ZIP_ABSOLUTE_PATH: {
    code: "ZIP_ABSOLUTE_PATH",
    expected_stage: "PREFLIGHT_ZIP",
    source_module: "zip-preflight",
    test_file: "qb02-binary-security.test.ts",
    test_name: "ZIP structural preflight: absolute path entry",
    fixture_builder: "buildZipWithAbsolutePath",
  },
  WORKBOOK_ENCRYPTED: {
    code: "WORKBOOK_ENCRYPTED",
    expected_stage: "PREFLIGHT_ZIP",
    source_module: "zip-preflight",
    test_file: "qb02-binary-security.test.ts",
    test_name: "ZIP structural preflight: encrypted zip entry",
    fixture_builder: "buildEncryptedZip",
  },
  MACRO_CONTENT: {
    code: "MACRO_CONTENT",
    expected_stage: "PREFLIGHT_OOXML",
    source_module: "preflight",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "preflight formula/macros/encryption",
    fixture_builder: "preflightWorkbook",
  },
  EXTERNAL_LINK: {
    code: "EXTERNAL_LINK",
    expected_stage: "PREFLIGHT_OOXML",
    source_module: "workbook-parser",
    test_file: "qb02-binary-security.test.ts",
    test_name: "OOXML relationship security: external hyperlink target",
    fixture_builder: "buildOoxmlExternalRelXlsx",
  },
  PATH_TRAVERSAL: {
    code: "PATH_TRAVERSAL",
    expected_stage: "PREFLIGHT_ZIP",
    source_module: "zip-preflight",
    test_file: "qb02-binary-security.test.ts",
    test_name: "ZIP structural preflight: path traversal entry",
    fixture_builder: "buildZipWithPathTraversal",
  },
  FORMULA_CELL: {
    code: "FORMULA_CELL",
    expected_stage: "PREFLIGHT_OOXML",
    source_module: "preflight",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "preflight formula/macros/encryption",
    fixture_builder: "preflightWorkbook",
  },
  MERGED_DATA_CELL: {
    code: "MERGED_DATA_CELL",
    expected_stage: "PREFLIGHT_OOXML",
    source_module: "preflight",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "preflight formula/macros/encryption",
    fixture_builder: "preflightWorkbook",
  },
  HIDDEN_SHEET_DATA: {
    code: "HIDDEN_SHEET_DATA",
    expected_stage: "PREFLIGHT_OOXML",
    source_module: "preflight",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "preflight workbook metadata",
    fixture_builder: "preflightWorkbook",
  },
  HIDDEN_ROW_DATA: {
    code: "HIDDEN_ROW_DATA",
    expected_stage: "PREFLIGHT_OOXML",
    source_module: "preflight",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "preflight workbook metadata",
    fixture_builder: "preflightWorkbook",
  },
  HIDDEN_COLUMN_DATA: {
    code: "HIDDEN_COLUMN_DATA",
    expected_stage: "PREFLIGHT_OOXML",
    source_module: "preflight",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "preflight workbook metadata",
    fixture_builder: "preflightWorkbook",
  },
  SHEET_COUNT_INVALID: {
    code: "SHEET_COUNT_INVALID",
    expected_stage: "PREFLIGHT_OOXML",
    source_module: "preflight",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "preflight workbook metadata",
    fixture_builder: "preflightWorkbook",
  },
  ROW_LIMIT: {
    code: "ROW_LIMIT",
    expected_stage: "PREFLIGHT_OOXML",
    source_module: "preflight",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "limits 1000 pass / 1001 fail",
    fixture_builder: "preflightWorkbook",
  },
  COLUMN_LIMIT: {
    code: "COLUMN_LIMIT",
    expected_stage: "PREFLIGHT_OOXML",
    source_module: "preflight",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "limits 256 columns limit",
    fixture_builder: "preflightWorkbook",
  },
  CELL_TOO_LARGE: {
    code: "CELL_TOO_LARGE",
    expected_stage: "PREFLIGHT_OOXML",
    source_module: "preflight",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "64 KiB cell boundary via preflight metadata",
    fixture_builder: "preflightWorkbook",
  },
  MALFORMED_UNICODE: {
    code: "MALFORMED_UNICODE",
    expected_stage: "PREFLIGHT_OOXML",
    source_module: "unicode",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "unicode malformed check",
    fixture_builder: "preflightWorkbook",
  },
  MISSING_HEADER: {
    code: "MISSING_HEADER",
    expected_stage: "ADAPTER_DETECT",
    source_module: "detect",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "missing required header",
    fixture_builder: "detectSchemaFromHeaders",
  },
  DUPLICATE_HEADER: {
    code: "DUPLICATE_HEADER",
    expected_stage: "PREFLIGHT_OOXML",
    source_module: "preflight",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "duplicate header check",
    fixture_builder: "preflightWorkbook",
  },
  UNKNOWN_COLUMN: {
    code: "UNKNOWN_COLUMN",
    expected_stage: "ADAPTER_DETECT",
    source_module: "detect",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "unknown column warning",
    fixture_builder: "adaptOfficialFlatV0",
  },
  FORBIDDEN_COLUMN: {
    code: "FORBIDDEN_COLUMN",
    expected_stage: "ADAPTER_DETECT",
    source_module: "preflight",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "forbidden column escalation",
    fixture_builder: "preflightWorkbook",
  },
  LEGACY_COLUMN_COUNT: {
    code: "LEGACY_COLUMN_COUNT",
    expected_stage: "ADAPTER_DETECT",
    source_module: "legacy-flat-15col",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "legacy column count match",
    fixture_builder: "runQuestionBankImportDryRun",
  },
  LEGACY_COLUMN_ORDER: {
    code: "LEGACY_COLUMN_ORDER",
    expected_stage: "ADAPTER_DETECT",
    source_module: "legacy-flat-15col",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "legacy column order match",
    fixture_builder: "runQuestionBankImportDryRun",
  },
  MISSING_VALUE: {
    code: "MISSING_VALUE",
    expected_stage: "ROW_VALIDATION",
    source_module: "official-flat-v0",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "missing value row check",
    fixture_builder: "adaptOfficialFlatV0",
  },
  INVALID_CONTRACT: {
    code: "INVALID_CONTRACT",
    expected_stage: "ADAPTER_DETECT",
    source_module: "detect",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "schemaHint mismatch rejects mixed workbook",
    fixture_builder: "runQuestionBankImportDryRun",
  },
  INVALID_INTERACTION_TYPE: {
    code: "INVALID_INTERACTION_TYPE",
    expected_stage: "ROW_VALIDATION",
    source_module: "validate",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "invalid interaction type",
    fixture_builder: "validateNormalizedRow",
  },
  INVALID_GRADING_MODE: {
    code: "INVALID_GRADING_MODE",
    expected_stage: "ROW_VALIDATION",
    source_module: "validate",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "invalid grading mode",
    fixture_builder: "validateNormalizedRow",
  },
  INCOMPATIBLE_TYPE_MODE: {
    code: "INCOMPATIBLE_TYPE_MODE",
    expected_stage: "ROW_VALIDATION",
    source_module: "validate",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "incompatible type mode",
    fixture_builder: "validateNormalizedRow",
  },
  OPTION_COUNT: {
    code: "OPTION_COUNT",
    expected_stage: "ROW_VALIDATION",
    source_module: "validate",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "option count limits",
    fixture_builder: "validateNormalizedRow",
  },
  DUPLICATE_OPTION: {
    code: "DUPLICATE_OPTION",
    expected_stage: "ROW_VALIDATION",
    source_module: "validate",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "duplicate option text is ambiguous",
    fixture_builder: "validateNormalizedRow",
  },
  MISSING_CORRECT_INDEX: {
    code: "MISSING_CORRECT_INDEX",
    expected_stage: "ROW_VALIDATION",
    source_module: "official-flat-v0",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "missing correct index",
    fixture_builder: "adaptOfficialFlatV0",
  },
  INVALID_CORRECT_INDEX: {
    code: "INVALID_CORRECT_INDEX",
    expected_stage: "ROW_VALIDATION",
    source_module: "official-flat-v0",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "rejects negative/decimal/mixed numerals",
    fixture_builder: "adaptOfficialFlatV0",
  },
  CORRECT_INDEX_NO_OPTION: {
    code: "CORRECT_INDEX_NO_OPTION",
    expected_stage: "ROW_VALIDATION",
    source_module: "official-flat-v0",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "correct index points to empty option",
    fixture_builder: "adaptOfficialFlatV0",
  },
  ANSWER_NOT_ALLOWED: {
    code: "ANSWER_NOT_ALLOWED",
    expected_stage: "ROW_VALIDATION",
    source_module: "validate",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "answer not allowed for manual grading",
    fixture_builder: "validateNormalizedRow",
  },
  ACCEPTED_ANSWER_REQUIRED: {
    code: "ACCEPTED_ANSWER_REQUIRED",
    expected_stage: "ROW_VALIDATION",
    source_module: "validate",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "accepted answer required for auto text",
    fixture_builder: "validateNormalizedRow",
  },
  DUPLICATE_ACCEPTED_ANSWER: {
    code: "DUPLICATE_ACCEPTED_ANSWER",
    expected_stage: "ROW_VALIDATION",
    source_module: "validate",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "duplicate accepted answer warning",
    fixture_builder: "validateNormalizedRow",
  },
  INVALID_SCORE: {
    code: "INVALID_SCORE",
    expected_stage: "ROW_VALIDATION",
    source_module: "validate",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "invalid score rejected",
    fixture_builder: "validateNormalizedRow",
  },
  PARTIAL_NOT_ALLOWED: {
    code: "PARTIAL_NOT_ALLOWED",
    expected_stage: "ROW_VALIDATION",
    source_module: "official-flat-v0",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "partial score not allowed",
    fixture_builder: "adaptOfficialFlatV0",
  },
  QUESTION_CODE_INVALID: {
    code: "QUESTION_CODE_INVALID",
    expected_stage: "ROW_VALIDATION",
    source_module: "validate",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "question code syntax regex check",
    fixture_builder: "validateNormalizedRow",
  },
  DUPLICATE_CODE_IN_FILE: {
    code: "DUPLICATE_CODE_IN_FILE",
    expected_stage: "ROW_VALIDATION",
    source_module: "validate",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "duplicate code in file",
    fixture_builder: "validateNormalizedRow",
  },
  DUPLICATE_CODE_EXISTS: {
    code: "DUPLICATE_CODE_EXISTS",
    expected_stage: "IDEMPOTENCY",
    source_module: "validate",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "duplicate code in existing catalog",
    fixture_builder: "validateNormalizedRow",
  },
  UNKNOWN_SUBJECT: {
    code: "UNKNOWN_SUBJECT",
    expected_stage: "ROW_VALIDATION",
    source_module: "validate",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "unknown subject code",
    fixture_builder: "validateNormalizedRow",
  },
  UNKNOWN_LESSON: {
    code: "UNKNOWN_LESSON",
    expected_stage: "ROW_VALIDATION",
    source_module: "validate",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "unknown lesson code",
    fixture_builder: "validateNormalizedRow",
  },
  CROSS_SUBJECT_MAPPING: {
    code: "CROSS_SUBJECT_MAPPING",
    expected_stage: "ROW_VALIDATION",
    source_module: "validate",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "cross subject mapping restriction",
    fixture_builder: "validateNormalizedRow",
  },
  CROSS_LESSON_MAPPING: {
    code: "CROSS_LESSON_MAPPING",
    expected_stage: "ROW_VALIDATION",
    source_module: "validate",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "mutation 10: cross-subject/lesson curriculum check stays fail-closed",
    fixture_builder: "validateNormalizedRow",
  },
  MEDIA_URL_INVALID: {
    code: "MEDIA_URL_INVALID",
    expected_stage: "ROW_VALIDATION",
    source_module: "media-policy",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "media policy fail-closed",
    fixture_builder: "validateNormalizedRow",
  },
  MEDIA_TYPE_REQUIRED: {
    code: "MEDIA_TYPE_REQUIRED",
    expected_stage: "ROW_VALIDATION",
    source_module: "media-policy",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "media type required",
    fixture_builder: "validateNormalizedRow",
  },
  FORMULA_INJECTION: {
    code: "FORMULA_INJECTION",
    expected_stage: "PREFLIGHT_OOXML",
    source_module: "preflight",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "csv parser integration rejects formula-like cells via trusted path",
    fixture_builder: "preflightWorkbook",
  },
  MIXED_NUMERAL_SCRIPTS: {
    code: "MIXED_NUMERAL_SCRIPTS",
    expected_stage: "ROW_VALIDATION",
    source_module: "unicode",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "mutation 6/7: mixed numerals and NFC remain active",
    fixture_builder: "mixedNumeralScripts",
  },
  SCIENTIFIC_NOTATION_LOSS: {
    code: "SCIENTIFIC_NOTATION_LOSS",
    expected_stage: "ROW_VALIDATION",
    source_module: "official-flat-v0",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "scientific notation string check",
    fixture_builder: "adaptOfficialFlatV0",
  },
  LEGACY_INFORMATION_LOSS: {
    code: "LEGACY_INFORMATION_LOSS",
    expected_stage: "ROW_VALIDATION",
    source_module: "legacy-flat-15col",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "legacy auto_text is information loss",
    fixture_builder: "adaptLegacyFlat15Col",
  },
  UNAUTHORIZED_IMPORT: {
    code: "UNAUTHORIZED_IMPORT",
    expected_stage: "AUTHORIZATION",
    source_module: "authorization",
    test_file: "qb02-authorization-matrix.test.ts",
    test_name: "Authorization DENY case: authorized:false within completed context",
    fixture_builder: "validateImportAuthorization",
  },
  AUTH_MISSING: {
    code: "AUTH_MISSING",
    expected_stage: "AUTHORIZATION",
    source_module: "authorization",
    test_file: "qb02-authorization-matrix.test.ts",
    test_name: "Authorization DENY case: omitted",
    fixture_builder: "validateImportAuthorization",
  },
  AUTH_MALFORMED: {
    code: "AUTH_MALFORMED",
    expected_stage: "AUTHORIZATION",
    source_module: "authorization",
    test_file: "qb02-authorization-matrix.test.ts",
    test_name: "Authorization DENY case: empty object",
    fixture_builder: "validateImportAuthorization",
  },
  AUTHENTICATION_REQUIRED: {
    code: "AUTHENTICATION_REQUIRED",
    expected_stage: "AUTHORIZATION",
    source_module: "authorization",
    test_file: "qb02-authorization-matrix.test.ts",
    test_name: "Authorization DENY case: authenticated:false",
    fixture_builder: "validateImportAuthorization",
  },
  CAPABILITY_INVALID: {
    code: "CAPABILITY_INVALID",
    expected_stage: "AUTHORIZATION",
    source_module: "authorization",
    test_file: "qb02-authorization-matrix.test.ts",
    test_name: "Authorization DENY case: capability wrong",
    fixture_builder: "validateImportAuthorization",
  },
  SCOPE_MISMATCH: {
    code: "SCOPE_MISMATCH",
    expected_stage: "AUTHORIZATION",
    source_module: "authorization",
    test_file: "qb02-authorization-matrix.test.ts",
    test_name: "Authorization DENY case: scope wrong",
    fixture_builder: "validateImportAuthorization",
  },
  AUTH_EXPIRED: {
    code: "AUTH_EXPIRED",
    expected_stage: "AUTHORIZATION",
    source_module: "authorization",
    test_file: "qb02-authorization-matrix.test.ts",
    test_name: "Authorization DENY case: expired:true",
    fixture_builder: "validateImportAuthorization",
  },
  PRIVILEGE_ESCALATION: {
    code: "PRIVILEGE_ESCALATION",
    expected_stage: "AUTHORIZATION",
    source_module: "preflight",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "forbidden column escalation",
    fixture_builder: "preflightWorkbook",
  },
  PREVIEW_TOKEN_INVALID: {
    code: "PREVIEW_TOKEN_INVALID",
    expected_stage: "IDEMPOTENCY",
    source_module: "preview",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "preview token invalid",
    fixture_builder: "buildPublicPreview",
  },
  STALE_VALIDATION: {
    code: "STALE_VALIDATION",
    expected_stage: "IDEMPOTENCY",
    source_module: "dry-run",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "stale validation check",
    fixture_builder: "runQuestionBankImportDryRun",
  },
  CONTENT_HASH_MISMATCH: {
    code: "CONTENT_HASH_MISMATCH",
    expected_stage: "IDEMPOTENCY",
    source_module: "dry-run",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "content hash mismatch check",
    fixture_builder: "runQuestionBankImportDryRun",
  },
  IMPORT_REPLAY_CONFLICT: {
    code: "IMPORT_REPLAY_CONFLICT",
    expected_stage: "IDEMPOTENCY",
    source_module: "dry-run",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "replay: safe noop / conflict / duplicate content",
    fixture_builder: "runQuestionBankImportDryRun",
  },
  ATOMIC_APPLY_FAILED: {
    code: "ATOMIC_APPLY_FAILED",
    expected_stage: "IDEMPOTENCY",
    source_module: "dry-run",
    test_file: "qb02-write-adapter.test.ts",
    test_name: "throwing adapter not called on dry run failure",
    fixture_builder: "runQuestionBankImportDryRun",
  },
  NORMALIZATION_CHANGED: {
    code: "NORMALIZATION_CHANGED",
    expected_stage: "ROW_VALIDATION",
    source_module: "unicode",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "normalizeText changes string representation",
    fixture_builder: "normalizeText",
  },
};
