import type { QbImportCode, ImportStage } from "../../../src/lib/question-bank/import/validation-codes.ts";

export type FailureCoverageMapping = {
  code: QbImportCode;
  expected_stage: ImportStage;
  source_module: string;
  test_file: string;
  test_name: string;
  fixture_builder: string;
};

export const FAILURE_COVERAGE_MANIFEST: Record<QbImportCode, FailureCoverageMapping> = {
  FILE_TYPE_UNSUPPORTED: {
    code: "FILE_TYPE_UNSUPPORTED",
    expected_stage: "PREFLIGHT_RAW",
    source_module: "zip-preflight",
    test_file: "qb02-binary-security.test.ts",
    test_name: "Binary Fixture extension_mismatch",
    fixture_builder: "binary-fixture:extension_mismatch",
  },
  FILE_TOO_LARGE: {
    code: "FILE_TOO_LARGE",
    expected_stage: "PREFLIGHT_RAW",
    source_module: "zip-preflight",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Preflight FILE_TOO_LARGE",
    fixture_builder: "preflightWorkbook",
  },
  ZIP_BOMB_SUSPECTED: {
    code: "ZIP_BOMB_SUSPECTED",
    expected_stage: "PREFLIGHT_ZIP",
    source_module: "zip-preflight",
    test_file: "qb02-binary-security.test.ts",
    test_name: "Binary Fixture zip_ratio_overflow",
    fixture_builder: "binary-fixture:zip_ratio_overflow",
  },
  ZIP_ENTRY_LIMIT: {
    code: "ZIP_ENTRY_LIMIT",
    expected_stage: "PREFLIGHT_ZIP",
    source_module: "zip-preflight",
    test_file: "qb02-binary-security.test.ts",
    test_name: "Binary Fixture zip_excessive_entries",
    fixture_builder: "binary-fixture:zip_excessive_entries",
  },
  ZIP_TOTAL_SIZE_LIMIT: {
    code: "ZIP_TOTAL_SIZE_LIMIT",
    expected_stage: "PREFLIGHT_ZIP",
    source_module: "zip-preflight",
    test_file: "qb02-binary-security.test.ts",
    test_name: "Binary Fixture zip_total_size_overflow",
    fixture_builder: "binary-fixture:zip_total_size_overflow",
  },
  ZIP_DECLARED_SIZE_LIMIT: {
    code: "ZIP_DECLARED_SIZE_LIMIT",
    expected_stage: "PREFLIGHT_ZIP",
    source_module: "zip-preflight",
    test_file: "qb02-binary-security.test.ts",
    test_name: "Binary Fixture zip_declared_size_overflow",
    fixture_builder: "binary-fixture:zip_declared_size_overflow",
  },
  ZIP_DUPLICATE_ENTRY: {
    code: "ZIP_DUPLICATE_ENTRY",
    expected_stage: "PREFLIGHT_ZIP",
    source_module: "zip-preflight",
    test_file: "qb02-binary-security.test.ts",
    test_name: "Binary Fixture zip_duplicate_entry",
    fixture_builder: "binary-fixture:zip_duplicate_entry",
  },
  ZIP_MALFORMED_CENTRAL_DIRECTORY: {
    code: "ZIP_MALFORMED_CENTRAL_DIRECTORY",
    expected_stage: "PREFLIGHT_ZIP",
    source_module: "zip-preflight",
    test_file: "qb02-binary-security.test.ts",
    test_name: "Binary Fixture zip_malformed_cd",
    fixture_builder: "binary-fixture:zip_malformed_cd",
  },
  ZIP_MISSING_EOCD: {
    code: "ZIP_MISSING_EOCD",
    expected_stage: "PREFLIGHT_ZIP",
    source_module: "zip-preflight",
    test_file: "qb02-binary-security.test.ts",
    test_name: "Binary Fixture zip_truncated",
    fixture_builder: "binary-fixture:zip_truncated",
  },
  ZIP_ABSOLUTE_PATH: {
    code: "ZIP_ABSOLUTE_PATH",
    expected_stage: "PREFLIGHT_ZIP",
    source_module: "zip-preflight",
    test_file: "qb02-binary-security.test.ts",
    test_name: "Binary Fixture zip_absolute_path",
    fixture_builder: "binary-fixture:zip_absolute_path",
  },
  WORKBOOK_ENCRYPTED: {
    code: "WORKBOOK_ENCRYPTED",
    expected_stage: "PREFLIGHT_ZIP",
    source_module: "workbook-parser",
    test_file: "qb02-binary-security.test.ts",
    test_name: "Binary Fixture zip_encrypted",
    fixture_builder: "binary-fixture:zip_encrypted",
  },
  MACRO_CONTENT: {
    code: "MACRO_CONTENT",
    expected_stage: "PREFLIGHT_OOXML",
    source_module: "workbook-parser",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Preflight MACRO_CONTENT",
    fixture_builder: "preflightWorkbook",
  },
  EXTERNAL_LINK: {
    code: "EXTERNAL_LINK",
    expected_stage: "PREFLIGHT_OOXML",
    source_module: "workbook-parser",
    test_file: "qb02-binary-security.test.ts",
    test_name: "Binary Fixture ooxml_external_rel",
    fixture_builder: "binary-fixture:ooxml_external_rel",
  },
  OOXML_RELATIONSHIP_STRUCTURE_INVALID: {
    code: "OOXML_RELATIONSHIP_STRUCTURE_INVALID",
    expected_stage: "PREFLIGHT_OOXML",
    source_module: "workbook-parser",
    test_file: "qb02-binary-security.test.ts",
    test_name: "Binary Fixture ooxml_malformed_xml",
    fixture_builder: "binary-fixture:ooxml_malformed_xml",
  },
  PATH_TRAVERSAL: {
    code: "PATH_TRAVERSAL",
    expected_stage: "PREFLIGHT_ZIP",
    source_module: "zip-preflight",
    test_file: "qb02-binary-security.test.ts",
    test_name: "Binary Fixture zip_path_traversal",
    fixture_builder: "binary-fixture:zip_path_traversal",
  },
  FORMULA_CELL: {
    code: "FORMULA_CELL",
    expected_stage: "PREFLIGHT_OOXML",
    source_module: "workbook-parser",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Preflight FORMULA_CELL",
    fixture_builder: "preflightWorkbook",
  },
  MERGED_DATA_CELL: {
    code: "MERGED_DATA_CELL",
    expected_stage: "PREFLIGHT_OOXML",
    source_module: "preflight",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Preflight MERGED_DATA_CELL",
    fixture_builder: "preflightWorkbook",
  },
  HIDDEN_SHEET_DATA: {
    code: "HIDDEN_SHEET_DATA",
    expected_stage: "PREFLIGHT_OOXML",
    source_module: "preflight",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Preflight HIDDEN_SHEET_DATA",
    fixture_builder: "preflightWorkbook",
  },
  HIDDEN_ROW_DATA: {
    code: "HIDDEN_ROW_DATA",
    expected_stage: "PREFLIGHT_OOXML",
    source_module: "preflight",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Preflight HIDDEN_ROW_DATA",
    fixture_builder: "preflightWorkbook",
  },
  HIDDEN_COLUMN_DATA: {
    code: "HIDDEN_COLUMN_DATA",
    expected_stage: "PREFLIGHT_OOXML",
    source_module: "preflight",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Preflight HIDDEN_COLUMN_DATA",
    fixture_builder: "preflightWorkbook",
  },
  SHEET_COUNT_INVALID: {
    code: "SHEET_COUNT_INVALID",
    expected_stage: "PREFLIGHT_OOXML",
    source_module: "preflight",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Preflight SHEET_COUNT_INVALID",
    fixture_builder: "preflightWorkbook",
  },
  ROW_LIMIT: {
    code: "ROW_LIMIT",
    expected_stage: "PREFLIGHT_OOXML",
    source_module: "preflight",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Preflight ROW_LIMIT",
    fixture_builder: "preflightWorkbook",
  },
  COLUMN_LIMIT: {
    code: "COLUMN_LIMIT",
    expected_stage: "PREFLIGHT_OOXML",
    source_module: "preflight",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Preflight COLUMN_LIMIT",
    fixture_builder: "preflightWorkbook",
  },
  CELL_TOO_LARGE: {
    code: "CELL_TOO_LARGE",
    expected_stage: "PREFLIGHT_OOXML",
    source_module: "preflight",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Preflight CELL_TOO_LARGE",
    fixture_builder: "preflightWorkbook",
  },
  MALFORMED_UNICODE: {
    code: "MALFORMED_UNICODE",
    expected_stage: "PREFLIGHT_OOXML",
    source_module: "unicode",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Preflight MALFORMED_UNICODE",
    fixture_builder: "preflightWorkbook",
  },
  MISSING_HEADER: {
    code: "MISSING_HEADER",
    expected_stage: "ADAPTER_DETECT",
    source_module: "detect",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "QB02 Oracle QB02-049",
    fixture_builder: "buildOperationalInput(QB02-049)",
  },
  DUPLICATE_HEADER: {
    code: "DUPLICATE_HEADER",
    expected_stage: "PREFLIGHT_OOXML",
    source_module: "detect",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Preflight DUPLICATE_HEADER",
    fixture_builder: "preflightWorkbook",
  },
  UNKNOWN_COLUMN: {
    code: "UNKNOWN_COLUMN",
    expected_stage: "ADAPTER_DETECT",
    source_module: "detect",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "DryRun UNKNOWN_COLUMN",
    fixture_builder: "runQuestionBankImportDryRun",
  },
  FORBIDDEN_COLUMN: {
    code: "FORBIDDEN_COLUMN",
    expected_stage: "ADAPTER_DETECT",
    source_module: "detect",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Preflight FORBIDDEN_COLUMN",
    fixture_builder: "preflightWorkbook",
  },
  LEGACY_COLUMN_COUNT: {
    code: "LEGACY_COLUMN_COUNT",
    expected_stage: "ADAPTER_DETECT",
    source_module: "legacy-flat-15col",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "DryRun LEGACY_COLUMN_COUNT",
    fixture_builder: "runQuestionBankImportDryRun",
  },
  LEGACY_COLUMN_ORDER: {
    code: "LEGACY_COLUMN_ORDER",
    expected_stage: "ADAPTER_DETECT",
    source_module: "legacy-flat-15col",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "DryRun LEGACY_COLUMN_ORDER",
    fixture_builder: "runQuestionBankImportDryRun",
  },
  MISSING_VALUE: {
    code: "MISSING_VALUE",
    expected_stage: "ROW_VALIDATION",
    source_module: "official-flat-v0",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Validation MISSING_VALUE",
    fixture_builder: "adaptOfficialFlatV0",
  },
  INVALID_CONTRACT: {
    code: "INVALID_CONTRACT",
    expected_stage: "ADAPTER_DETECT",
    source_module: "detect",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "QB02 Oracle QB02-046",
    fixture_builder: "buildOperationalInput(QB02-046)",
  },
  INVALID_INTERACTION_TYPE: {
    code: "INVALID_INTERACTION_TYPE",
    expected_stage: "ROW_VALIDATION",
    source_module: "official-flat-v0",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Validation INVALID_INTERACTION_TYPE",
    fixture_builder: "adaptOfficialFlatV0",
  },
  INVALID_GRADING_MODE: {
    code: "INVALID_GRADING_MODE",
    expected_stage: "ROW_VALIDATION",
    source_module: "official-flat-v0",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Validation INVALID_GRADING_MODE",
    fixture_builder: "adaptOfficialFlatV0",
  },
  INCOMPATIBLE_TYPE_MODE: {
    code: "INCOMPATIBLE_TYPE_MODE",
    expected_stage: "ROW_VALIDATION",
    source_module: "validate",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "QB02 Oracle QB02-058",
    fixture_builder: "buildOperationalInput(QB02-058)",
  },
  OPTION_COUNT: {
    code: "OPTION_COUNT",
    expected_stage: "ROW_VALIDATION",
    source_module: "correct-answer",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "QB02 Oracle QB02-059",
    fixture_builder: "buildOperationalInput(QB02-059)",
  },
  DUPLICATE_OPTION: {
    code: "DUPLICATE_OPTION",
    expected_stage: "ROW_VALIDATION",
    source_module: "correct-answer",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Validation DUPLICATE_OPTION",
    fixture_builder: "validateNormalizedRow",
  },
  MISSING_CORRECT_INDEX: {
    code: "MISSING_CORRECT_INDEX",
    expected_stage: "ROW_VALIDATION",
    source_module: "correct-answer",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "QB02 Oracle QB02-061",
    fixture_builder: "buildOperationalInput(QB02-061)",
  },
  INVALID_CORRECT_INDEX: {
    code: "INVALID_CORRECT_INDEX",
    expected_stage: "ROW_VALIDATION",
    source_module: "correct-answer",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Validation INVALID_CORRECT_INDEX",
    fixture_builder: "adaptOfficialFlatV0",
  },
  CORRECT_INDEX_NO_OPTION: {
    code: "CORRECT_INDEX_NO_OPTION",
    expected_stage: "ROW_VALIDATION",
    source_module: "correct-answer",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Validation CORRECT_INDEX_NO_OPTION",
    fixture_builder: "adaptOfficialFlatV0",
  },
  ANSWER_NOT_ALLOWED: {
    code: "ANSWER_NOT_ALLOWED",
    expected_stage: "ROW_VALIDATION",
    source_module: "validate",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Validation ANSWER_NOT_ALLOWED",
    fixture_builder: "adaptOfficialFlatV0",
  },
  ACCEPTED_ANSWER_REQUIRED: {
    code: "ACCEPTED_ANSWER_REQUIRED",
    expected_stage: "ROW_VALIDATION",
    source_module: "correct-answer",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Validation ACCEPTED_ANSWER_REQUIRED",
    fixture_builder: "adaptOfficialFlatV0",
  },
  DUPLICATE_ACCEPTED_ANSWER: {
    code: "DUPLICATE_ACCEPTED_ANSWER",
    expected_stage: "ROW_VALIDATION",
    source_module: "correct-answer",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Validation DUPLICATE_ACCEPTED_ANSWER",
    fixture_builder: "adaptOfficialFlatV0",
  },
  INVALID_SCORE: {
    code: "INVALID_SCORE",
    expected_stage: "ROW_VALIDATION",
    source_module: "validate",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Validation INVALID_SCORE",
    fixture_builder: "adaptOfficialFlatV0",
  },
  PARTIAL_NOT_ALLOWED: {
    code: "PARTIAL_NOT_ALLOWED",
    expected_stage: "ROW_VALIDATION",
    source_module: "validate",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Validation PARTIAL_NOT_ALLOWED",
    fixture_builder: "adaptOfficialFlatV0",
  },
  QUESTION_CODE_INVALID: {
    code: "QUESTION_CODE_INVALID",
    expected_stage: "ROW_VALIDATION",
    source_module: "validate",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Validation QUESTION_CODE_INVALID",
    fixture_builder: "validateNormalizedRow",
  },
  DUPLICATE_CODE_IN_FILE: {
    code: "DUPLICATE_CODE_IN_FILE",
    expected_stage: "ROW_VALIDATION",
    source_module: "validate",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "DryRun DUPLICATE_CODE_IN_FILE",
    fixture_builder: "runQuestionBankImportDryRun",
  },
  DUPLICATE_CODE_EXISTS: {
    code: "DUPLICATE_CODE_EXISTS",
    expected_stage: "IDEMPOTENCY",
    source_module: "validate",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "QB02 Oracle QB02-070",
    fixture_builder: "buildOperationalInput(QB02-070)",
  },
  UNKNOWN_SUBJECT: {
    code: "UNKNOWN_SUBJECT",
    expected_stage: "ROW_VALIDATION",
    source_module: "validate",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Validation UNKNOWN_SUBJECT",
    fixture_builder: "validateNormalizedRow",
  },
  UNKNOWN_LESSON: {
    code: "UNKNOWN_LESSON",
    expected_stage: "ROW_VALIDATION",
    source_module: "validate",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Validation UNKNOWN_LESSON",
    fixture_builder: "validateNormalizedRow",
  },
  CROSS_SUBJECT_MAPPING: {
    code: "CROSS_SUBJECT_MAPPING",
    expected_stage: "ROW_VALIDATION",
    source_module: "validate",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "QB02 Oracle QB02-073",
    fixture_builder: "buildOperationalInput(QB02-073)",
  },
  CROSS_LESSON_MAPPING: {
    code: "CROSS_LESSON_MAPPING",
    expected_stage: "ROW_VALIDATION",
    source_module: "validate",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "QB02 Oracle QB02-074",
    fixture_builder: "buildOperationalInput(QB02-074)",
  },
  MEDIA_URL_INVALID: {
    code: "MEDIA_URL_INVALID",
    expected_stage: "ROW_VALIDATION",
    source_module: "media-policy",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "QB02 Oracle QB02-075",
    fixture_builder: "buildOperationalInput(QB02-075)",
  },
  MEDIA_TYPE_REQUIRED: {
    code: "MEDIA_TYPE_REQUIRED",
    expected_stage: "ROW_VALIDATION",
    source_module: "media-policy",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "QB02 Oracle QB02-076",
    fixture_builder: "buildOperationalInput(QB02-076)",
  },
  FORMULA_INJECTION: {
    code: "FORMULA_INJECTION",
    expected_stage: "PREFLIGHT_OOXML",
    source_module: "validate",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "QB02 Oracle QB02-077",
    fixture_builder: "buildOperationalInput(QB02-077)",
  },
  MIXED_NUMERAL_SCRIPTS: {
    code: "MIXED_NUMERAL_SCRIPTS",
    expected_stage: "ROW_VALIDATION",
    source_module: "unicode",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Validation MIXED_NUMERAL_SCRIPTS",
    fixture_builder: "validateNormalizedRow",
  },
  SCIENTIFIC_NOTATION_LOSS: {
    code: "SCIENTIFIC_NOTATION_LOSS",
    expected_stage: "ROW_VALIDATION",
    source_module: "unicode",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Validation SCIENTIFIC_NOTATION_LOSS",
    fixture_builder: "validateNormalizedRow",
  },
  LEGACY_INFORMATION_LOSS: {
    code: "LEGACY_INFORMATION_LOSS",
    expected_stage: "ROW_VALIDATION",
    source_module: "legacy-flat-15col",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Validation LEGACY_INFORMATION_LOSS",
    fixture_builder: "adaptLegacyFlat15Col",
  },
  UNAUTHORIZED_IMPORT: {
    code: "UNAUTHORIZED_IMPORT",
    expected_stage: "AUTHORIZATION",
    source_module: "authorization",
    test_file: "qb02-authorization-matrix.test.ts",
    test_name: "Auth Case unauthorized",
    fixture_builder: "auth-case:unauthorized",
  },
  AUTH_MISSING: {
    code: "AUTH_MISSING",
    expected_stage: "AUTHORIZATION",
    source_module: "authorization",
    test_file: "qb02-authorization-matrix.test.ts",
    test_name: "Auth Case omitted",
    fixture_builder: "auth-case:omitted",
  },
  AUTH_MALFORMED: {
    code: "AUTH_MALFORMED",
    expected_stage: "AUTHORIZATION",
    source_module: "authorization",
    test_file: "qb02-authorization-matrix.test.ts",
    test_name: "Auth Case malformed",
    fixture_builder: "auth-case:malformed",
  },
  AUTHENTICATION_REQUIRED: {
    code: "AUTHENTICATION_REQUIRED",
    expected_stage: "AUTHORIZATION",
    source_module: "authorization",
    test_file: "qb02-authorization-matrix.test.ts",
    test_name: "Auth Case unauthenticated",
    fixture_builder: "auth-case:unauthenticated",
  },
  CAPABILITY_INVALID: {
    code: "CAPABILITY_INVALID",
    expected_stage: "AUTHORIZATION",
    source_module: "authorization",
    test_file: "qb02-authorization-matrix.test.ts",
    test_name: "Auth Case invalid_capability",
    fixture_builder: "auth-case:invalid_capability",
  },
  SCOPE_MISMATCH: {
    code: "SCOPE_MISMATCH",
    expected_stage: "AUTHORIZATION",
    source_module: "authorization",
    test_file: "qb02-authorization-matrix.test.ts",
    test_name: "Auth Case scope_mismatch",
    fixture_builder: "auth-case:scope_mismatch",
  },
  AUTH_EXPIRED: {
    code: "AUTH_EXPIRED",
    expected_stage: "AUTHORIZATION",
    source_module: "authorization",
    test_file: "qb02-authorization-matrix.test.ts",
    test_name: "Auth Case expired",
    fixture_builder: "auth-case:expired",
  },
  PRIVILEGE_ESCALATION: {
    code: "PRIVILEGE_ESCALATION",
    expected_stage: "AUTHORIZATION",
    source_module: "preflight",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "QB02 Oracle QB02-082",
    fixture_builder: "buildOperationalInput(QB02-082)",
  },
  PREVIEW_TOKEN_INVALID: {
    code: "PREVIEW_TOKEN_INVALID",
    expected_stage: "IDEMPOTENCY",
    source_module: "apply-verifier",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Apply Verifier Token",
    fixture_builder: "apply-verifier:Token",
  },
  STALE_VALIDATION: {
    code: "STALE_VALIDATION",
    expected_stage: "IDEMPOTENCY",
    source_module: "apply-verifier",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Apply Verifier Stale",
    fixture_builder: "apply-verifier:Stale",
  },
  CONTENT_HASH_MISMATCH: {
    code: "CONTENT_HASH_MISMATCH",
    expected_stage: "IDEMPOTENCY",
    source_module: "apply-verifier",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Apply Verifier ContentHash",
    fixture_builder: "apply-verifier:ContentHash",
  },
  IMPORT_REPLAY_CONFLICT: {
    code: "IMPORT_REPLAY_CONFLICT",
    expected_stage: "IDEMPOTENCY",
    source_module: "dry-run",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "DryRun IMPORT_REPLAY_CONFLICT",
    fixture_builder: "runQuestionBankImportDryRun",
  },
  ATOMIC_APPLY_FAILED: {
    code: "ATOMIC_APPLY_FAILED",
    expected_stage: "IDEMPOTENCY",
    source_module: "apply-verifier",
    test_file: "qb02-write-adapter.test.ts",
    test_name: "Apply Verifier Atomic",
    fixture_builder: "apply-verifier:Atomic",
  },
  NORMALIZATION_CHANGED: {
    code: "NORMALIZATION_CHANGED",
    expected_stage: "ROW_VALIDATION",
    source_module: "unicode",
    test_file: "qb02-import-foundation.test.ts",
    test_name: "Validation NORMALIZATION_CHANGED",
    fixture_builder: "validateNormalizedRow",
  },
};
