/**
 * Error and warning codes for interactive HTML package validation and security scans.
 */
export const ValidationCodes = {
  // Preflight / File System Errors
  PACKAGE_EXCEEDS_MAX_SIZE: "PACKAGE_EXCEEDS_MAX_SIZE",
  UNCOMPRESSED_EXCEEDS_MAX_SIZE: "UNCOMPRESSED_EXCEEDS_MAX_SIZE",
  EXCEEDS_MAX_FILES: "EXCEEDS_MAX_FILES",
  EXCEEDS_MAX_RESOURCES: "EXCEEDS_MAX_RESOURCES",
  EXCEEDS_MAX_DEPTH: "EXCEEDS_MAX_DEPTH",
  EXCEEDS_SINGLE_FILE_LIMIT: "EXCEEDS_SINGLE_FILE_LIMIT",
  ZIP_BOMB_RATIO_EXCEEDED: "ZIP_BOMB_RATIO_EXCEEDED",
  PATH_TRAVERSAL_DETECTED: "PATH_TRAVERSAL_DETECTED",
  ABSOLUTE_PATH_DETECTED: "ABSOLUTE_PATH_DETECTED",
  SYMLINK_NOT_ALLOWED: "SYMLINK_NOT_ALLOWED",
  NESTED_ARCHIVE_NOT_ALLOWED: "NESTED_ARCHIVE_NOT_ALLOWED",
  FORBIDDEN_FILE_EXTENSION: "FORBIDDEN_FILE_EXTENSION",
  CASE_INSENSITIVE_PATH_COLLISION: "CASE_INSENSITIVE_PATH_COLLISION",
  DUPLICATE_PATH_DETECTED: "DUPLICATE_PATH_DETECTED",
  MIME_EXTENSION_MISMATCH: "MIME_EXTENSION_MISMATCH",
  WASM_NOT_ALLOWED_IN_MVP: "WASM_NOT_ALLOWED_IN_MVP",
  SERVICE_WORKER_NOT_ALLOWED: "SERVICE_WORKER_NOT_ALLOWED",

  // Entry File & Manifest Errors
  MISSING_INDEX_HTML: "MISSING_INDEX_HTML",
  MISSING_MANIFEST_JSON: "MISSING_MANIFEST_JSON",
  INVALID_MANIFEST_JSON: "INVALID_MANIFEST_JSON",
  RESOURCE_CODE_MISMATCH: "RESOURCE_CODE_MISMATCH",
  MISSING_REFERENCED_ASSET: "MISSING_REFERENCED_ASSET",
  EXTRA_ORPHAN_ASSET: "EXTRA_ORPHAN_ASSET",

  // Security Scanner Errors
  REMOTE_NETWORK_URL_DETECTED: "REMOTE_NETWORK_URL_DETECTED",
  INLINE_EVENT_HANDLER_DETECTED: "INLINE_EVENT_HANDLER_DETECTED",
  JAVASCRIPT_URL_DETECTED: "JAVASCRIPT_URL_DETECTED",
  FORBIDDEN_API_EVAL: "FORBIDDEN_API_EVAL",
  FORBIDDEN_API_FUNCTION_CTOR: "FORBIDDEN_API_FUNCTION_CTOR",
  FORBIDDEN_API_DOCUMENT_WRITE: "FORBIDDEN_API_DOCUMENT_WRITE",
  FORBIDDEN_API_WINDOW_PARENT: "FORBIDDEN_API_WINDOW_PARENT",
  FORBIDDEN_API_COOKIE: "FORBIDDEN_API_COOKIE",
  FORBIDDEN_API_STORAGE: "FORBIDDEN_API_STORAGE",
  FORBIDDEN_API_NETWORK_FETCH: "FORBIDDEN_API_NETWORK_FETCH",
  FORBIDDEN_API_CAPACITOR: "FORBIDDEN_API_CAPACITOR",
  FORBIDDEN_API_SUPABASE: "FORBIDDEN_API_SUPABASE",
  FORBIDDEN_IFRAME_ELEMENT: "FORBIDDEN_IFRAME_ELEMENT",
  FORBIDDEN_FORM_SUBMISSION: "FORBIDDEN_FORM_SUBMISSION",
  FORBIDDEN_EMBEDDED_VIDEO: "FORBIDDEN_EMBEDDED_VIDEO",

  // Excel Row / Curriculum Errors
  LESSON_NOT_FOUND: "LESSON_NOT_FOUND",
  SUBJECT_NOT_FOUND: "SUBJECT_NOT_FOUND",
  MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",
  DUPLICATE_RESOURCE_CODE: "DUPLICATE_RESOURCE_CODE",
  INVALID_RESOURCE_TYPE: "INVALID_RESOURCE_TYPE",
  ALT_TEXT_REQUIRED_FOR_MIND_MAP: "ALT_TEXT_REQUIRED_FOR_MIND_MAP",

  // Runtime & Bridge Errors
  NONCE_MISMATCH: "NONCE_MISMATCH",
  EVENT_RATE_LIMIT_EXCEEDED: "EVENT_RATE_LIMIT_EXCEEDED",
  INVALID_EVENT_SCHEMA: "INVALID_EVENT_SCHEMA",
  CAPACITOR_BRIDGE_NOT_ISOLATED: "CAPACITOR_BRIDGE_NOT_ISOLATED",
} as const;

export type ValidationCode = (typeof ValidationCodes)[keyof typeof ValidationCodes];
