-- DOCUMENTATION DRAFT ONLY
-- NOT APPLIED
-- DO NOT EXECUTE WITHOUT EXPLICIT APPROVAL
-- DESIGN FREEZE SOURCE ONLY
-- DO NOT PLACE THIS FILE UNDER supabase/migrations
--
-- QB-01 Schema Foundation — aligned with docs/QB-01-DESIGN-FREEZE-DECISION-07.md
-- All statements below are COMMENTED. Zero executable SQL in this file.
--
-- Frozen rules:
--   * Logical hub = public.questions
--   * Content SoT = question_revisions + revision-scoped children
--   * Legacy cache correct_index = 0-based (New -> Legacy sync only)
--   * Attempts after cutover = Model A exam_session_questions snapshots
--   * No student SELECT on is_correct / solutions / accepted_answers
--   * No DROP/RENAME of legacy columns in QB-01

-- ---------------------------------------------------------------------------
-- 0) Flexible interaction taxonomy (optional reference; not closed CHECK of 26)
-- ---------------------------------------------------------------------------
-- CREATE TABLE IF NOT EXISTS public.question_interaction_types (
--   code text PRIMARY KEY,
--   educational_label_ar text,
--   default_grading_mode text NOT NULL
--     CHECK (default_grading_mode IN ('AUTO_SINGLE', 'AUTO_TEXT', 'MANUAL')),
--   is_launch_enabled boolean NOT NULL DEFAULT false,
--   created_at timestamptz NOT NULL DEFAULT now()
-- );

-- ---------------------------------------------------------------------------
-- 1) Logical hub additive columns (non-breaking)
-- ---------------------------------------------------------------------------
-- ALTER TABLE public.questions
--   ADD COLUMN IF NOT EXISTS created_by uuid REFERENCES auth.users(id);
-- ALTER TABLE public.questions
--   ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
-- ALTER TABLE public.questions
--   ADD COLUMN IF NOT EXISTS current_published_revision_id uuid;
-- -- NOTE: updated_at is NOT versioning.
-- -- Legacy columns options / correct_index / explanation / lesson_id / subject_id / unit remain.
-- -- correct_index cache convention: 0-based (LOCKED).

-- ---------------------------------------------------------------------------
-- 2) question_revisions
-- ---------------------------------------------------------------------------
-- CREATE TABLE IF NOT EXISTS public.question_revisions (
--   id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
--   question_id uuid NOT NULL REFERENCES public.questions(id) ON DELETE RESTRICT,
--   revision_number int NOT NULL,
--   status text NOT NULL
--     CHECK (status IN (
--       'DRAFT', 'READY_FOR_REVIEW', 'APPROVED', 'PUBLISHED', 'SUPERSEDED', 'REJECTED'
--     )),
--   interaction_type text,
--   grading_mode text
--     CHECK (grading_mode IS NULL OR grading_mode IN ('AUTO_SINGLE', 'AUTO_TEXT', 'MANUAL')),
--   educational_label text,
--   question_text text NOT NULL,
--   stimulus_text text,
--   max_score numeric NOT NULL DEFAULT 1 CHECK (max_score > 0),
--   allow_partial boolean NOT NULL DEFAULT false,
--   requires_media boolean NOT NULL DEFAULT false,
--   manual_grading_required boolean NOT NULL DEFAULT false,
--   payload_hash text,
--   source_import_hash text,
--   created_at timestamptz NOT NULL DEFAULT now(),
--   created_by uuid REFERENCES auth.users(id),
--   reviewed_at timestamptz,
--   reviewed_by uuid REFERENCES auth.users(id),
--   published_at timestamptz,
--   published_by uuid REFERENCES auth.users(id),
--   superseded_at timestamptz,
--   UNIQUE (question_id, revision_number)
-- );
-- CREATE UNIQUE INDEX IF NOT EXISTS question_revisions_one_published
--   ON public.question_revisions (question_id)
--   WHERE status = 'PUBLISHED';
-- -- ALTER TABLE public.questions
-- --   ADD CONSTRAINT questions_current_published_revision_fk
-- --   FOREIGN KEY (current_published_revision_id)
-- --   REFERENCES public.question_revisions(id);

-- ---------------------------------------------------------------------------
-- 3) Targets (logical question_id for P0 stable curriculum binding)
-- ---------------------------------------------------------------------------
-- CREATE TABLE IF NOT EXISTS public.question_targets (
--   id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
--   question_id uuid NOT NULL REFERENCES public.questions(id) ON DELETE CASCADE,
--   target_type text NOT NULL CHECK (target_type IN ('SUBJECT', 'UNIT', 'LESSON')),
--   subject_id uuid REFERENCES public.subjects(id) ON DELETE CASCADE,
--   unit_id uuid REFERENCES public.units(id) ON DELETE CASCADE,
--   lesson_id uuid REFERENCES public.lessons(id) ON DELETE CASCADE,
--   is_primary boolean NOT NULL DEFAULT false,
--   created_at timestamptz NOT NULL DEFAULT now(),
--   CONSTRAINT question_targets_type_shape CHECK (
--     (target_type = 'SUBJECT' AND subject_id IS NOT NULL AND unit_id IS NULL AND lesson_id IS NULL)
--     OR (target_type = 'UNIT' AND unit_id IS NOT NULL AND lesson_id IS NULL)
--     OR (target_type = 'LESSON' AND lesson_id IS NOT NULL)
--   )
-- );
-- CREATE UNIQUE INDEX IF NOT EXISTS question_targets_one_primary
--   ON public.question_targets (question_id) WHERE is_primary;

-- ---------------------------------------------------------------------------
-- 4) Revision-scoped children
-- ---------------------------------------------------------------------------
-- CREATE TABLE IF NOT EXISTS public.question_options (
--   id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
--   question_revision_id uuid NOT NULL REFERENCES public.question_revisions(id) ON DELETE CASCADE,
--   option_code text NOT NULL,
--   body text NOT NULL,
--   sort_order int NOT NULL DEFAULT 0,
--   is_correct boolean NOT NULL DEFAULT false,
--   created_at timestamptz NOT NULL DEFAULT now(),
--   UNIQUE (question_revision_id, option_code)
-- );
--
-- CREATE TABLE IF NOT EXISTS public.question_accepted_answers (
--   id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
--   question_revision_id uuid NOT NULL REFERENCES public.question_revisions(id) ON DELETE CASCADE,
--   answer_text text NOT NULL,
--   normalized_answer text,
--   normalization_policy text NOT NULL DEFAULT 'TRIM_COLLAPSE'
--     CHECK (normalization_policy IN ('EXACT', 'TRIM', 'TRIM_COLLAPSE', 'CASEFOLD_AR')),
--   is_primary boolean NOT NULL DEFAULT false,
--   sort_order int NOT NULL DEFAULT 0,
--   created_at timestamptz NOT NULL DEFAULT now()
-- );
--
-- CREATE TABLE IF NOT EXISTS public.question_solutions (
--   question_revision_id uuid PRIMARY KEY REFERENCES public.question_revisions(id) ON DELETE CASCADE,
--   model_answer text,
--   explanation text,
--   hint text,
--   common_mistakes text,
--   simplified_rubric text,
--   reveal_policy text NOT NULL DEFAULT 'AFTER_SUBMIT'
--     CHECK (reveal_policy IN ('AFTER_ANSWER', 'AFTER_SUBMIT', 'NEVER_STUDENT', 'STAFF_ONLY')),
--   created_at timestamptz NOT NULL DEFAULT now(),
--   updated_at timestamptz NOT NULL DEFAULT now()
-- );
--
-- CREATE TABLE IF NOT EXISTS public.question_media (
--   id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
--   question_revision_id uuid NOT NULL REFERENCES public.question_revisions(id) ON DELETE CASCADE,
--   media_code text NOT NULL,
--   storage_path text NOT NULL,
--   mime_type text NOT NULL,
--   file_size bigint,
--   sha256 text,
--   alt_text_ar text NOT NULL,
--   caption text,
--   sort_order int NOT NULL DEFAULT 0,
--   requires_media boolean NOT NULL DEFAULT false,
--   created_at timestamptz NOT NULL DEFAULT now(),
--   created_by uuid REFERENCES auth.users(id),
--   UNIQUE (question_revision_id, media_code)
-- );
-- -- Storage bucket question-media is DESIGN ONLY — not created here.

-- ---------------------------------------------------------------------------
-- 5) Model A — exam session question snapshots (attempt pinning)
-- ---------------------------------------------------------------------------
-- CREATE TABLE IF NOT EXISTS public.exam_session_questions (
--   id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
--   exam_session_id uuid NOT NULL REFERENCES public.exam_sessions(id) ON DELETE CASCADE,
--   question_revision_id uuid NOT NULL REFERENCES public.question_revisions(id) ON DELETE RESTRICT,
--   logical_question_id uuid NOT NULL REFERENCES public.questions(id) ON DELETE RESTRICT,
--   question_order int NOT NULL,
--   rendered_question_text text NOT NULL,
--   rendered_stimulus text,
--   rendered_options jsonb NOT NULL DEFAULT '[]'::jsonb,
--   option_order_mapping jsonb NOT NULL DEFAULT '[]'::jsonb,
--   max_score numeric NOT NULL DEFAULT 1,
--   payload_hash text NOT NULL,
--   pin_mode text NOT NULL DEFAULT 'REVISION_PINNED'
--     CHECK (pin_mode IN ('REVISION_PINNED', 'LEGACY')),
--   created_at timestamptz NOT NULL DEFAULT now(),
--   UNIQUE (exam_session_id, question_revision_id)
-- );
--
-- -- Extend answers (shape; exact ALTER chosen in executable migration package):
-- -- ALTER TABLE public.exam_session_answers
-- --   ADD COLUMN IF NOT EXISTS exam_session_question_id uuid REFERENCES public.exam_session_questions(id),
-- --   ADD COLUMN IF NOT EXISTS question_revision_id uuid REFERENCES public.question_revisions(id),
-- --   ADD COLUMN IF NOT EXISTS selected_option_code text,
-- --   ADD COLUMN IF NOT EXISTS response_text text,
-- --   ADD COLUMN IF NOT EXISTS response_payload jsonb,
-- --   ADD COLUMN IF NOT EXISTS grading_status text,
-- --   ADD COLUMN IF NOT EXISTS auto_score numeric,
-- --   ADD COLUMN IF NOT EXISTS manual_score numeric,
-- --   ADD COLUMN IF NOT EXISTS final_score numeric,
-- --   ADD COLUMN IF NOT EXISTS requires_manual_review boolean NOT NULL DEFAULT false,
-- --   ADD COLUMN IF NOT EXISTS pin_mode text DEFAULT 'LEGACY';
-- -- Legacy rows keep question_id + selected_index; scores not reinterpreted.
-- -- selected_index MUST NOT be used as SoT for text responses.

-- ---------------------------------------------------------------------------
-- 6) Manual grading reviews
-- ---------------------------------------------------------------------------
-- CREATE TABLE IF NOT EXISTS public.question_response_reviews (
--   id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
--   response_id uuid NOT NULL, -- FK to exam_session_answers.id or unified response id
--   grader_id uuid NOT NULL REFERENCES auth.users(id),
--   score_awarded numeric NOT NULL,
--   feedback text,
--   previous_score numeric,
--   reason text,
--   is_final boolean NOT NULL DEFAULT false,
--   created_at timestamptz NOT NULL DEFAULT now()
-- );
-- -- grading_status values (app/RPC enforced):
-- -- NOT_REQUIRED | PENDING_MANUAL_REVIEW | IN_REVIEW | GRADED |
-- -- RETURNED_FOR_SECOND_REVIEW | FINALIZED

-- ---------------------------------------------------------------------------
-- 7) Capability helper placeholders (map to current roles; no new enum required)
-- ---------------------------------------------------------------------------
-- -- CREATE OR REPLACE FUNCTION public.can_edit_question_bank(_user_id uuid)
-- -- RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public'
-- -- AS $$ SELECT public.is_content_staff(_user_id); $$;
-- -- CREATE OR REPLACE FUNCTION public.can_review_question_content(_user_id uuid) ...
-- -- CREATE OR REPLACE FUNCTION public.can_publish_question_revision(_user_id uuid) ...
-- -- CREATE OR REPLACE FUNCTION public.can_grade_manual_response(_user_id uuid) ...
-- -- CREATE OR REPLACE FUNCTION public.can_read_hidden_solutions(_user_id uuid) ...
-- -- Grader helpers MUST NOT grant UPDATE on question_revisions / options / solutions.

-- ---------------------------------------------------------------------------
-- 8) RLS / GRANT matrix placeholders (deny-by-default)
-- ---------------------------------------------------------------------------
-- ALTER TABLE public.question_revisions ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.question_options ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.question_accepted_answers ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.question_solutions ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.question_media ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.question_targets ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.exam_session_questions ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.question_response_reviews ENABLE ROW LEVEL SECURITY;
--
-- REVOKE ALL ON public.question_options FROM PUBLIC;
-- REVOKE ALL ON public.question_accepted_answers FROM PUBLIC;
-- REVOKE ALL ON public.question_solutions FROM PUBLIC;
-- -- NO GRANT of is_correct / accepted_answers / solutions to authenticated.
-- -- Student option bodies via SECURITY DEFINER RPC only.
-- -- Example staff policy sketch:
-- -- CREATE POLICY question_options_staff_all ON public.question_options
-- --   FOR ALL TO authenticated
-- --   USING (public.can_edit_question_bank(auth.uid()))
-- --   WITH CHECK (public.can_edit_question_bank(auth.uid()));

-- ---------------------------------------------------------------------------
-- 9) Compatibility sync — New revision SoT -> Legacy cache (0-based)
-- ---------------------------------------------------------------------------
-- CREATE OR REPLACE FUNCTION public.qb_sync_question_legacy(_question_id uuid)
-- RETURNS void
-- LANGUAGE plpgsql
-- SECURITY DEFINER
-- SET search_path TO 'public'
-- AS $$
-- DECLARE
--   v_rev uuid;
--   v_options jsonb;
--   v_correct int; -- 0-based cache
--   v_explanation text;
-- BEGIN
--   SELECT current_published_revision_id INTO v_rev FROM public.questions WHERE id = _question_id;
--   -- Build options jsonb array ordered by sort_order from question_options(v_rev).
--   -- Set v_correct = zero-based index of first is_correct option (SINGLE_CHOICE).
--   -- NEVER apply Excel 1-based values here.
--   -- Copy explanation from question_solutions(v_rev).
--   -- UPDATE questions SET options = v_options, correct_index = v_correct, explanation = ...
--   NULL;
-- END;
-- $$;
-- REVOKE ALL ON FUNCTION public.qb_sync_question_legacy(uuid) FROM PUBLIC;
-- -- GRANT EXECUTE ... TO service_role / content staff path only (executable package).

-- END OF DOCUMENTATION DRAFT - NOT APPLIED - DESIGN FREEZE SOURCE ONLY
