/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedGradesRouteImport } from './routes/_authenticated/grades'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSubjectsSubjectIdRouteImport } from './routes/_authenticated/subjects.$subjectId'
import { Route as AuthenticatedPaymentsNewRouteImport } from './routes/_authenticated/payments.new'
import { Route as AuthenticatedLessonsLessonIdRouteImport } from './routes/_authenticated/lessons.$lessonId'
import { Route as AuthenticatedExamsHistoryRouteImport } from './routes/_authenticated/exams.history'
import { Route as AuthenticatedAdminUnitsRouteImport } from './routes/_authenticated/admin.units'
import { Route as AuthenticatedAdminSubjectsRouteImport } from './routes/_authenticated/admin.subjects'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin.students'
import { Route as AuthenticatedAdminQuestionsRouteImport } from './routes/_authenticated/admin.questions'
import { Route as AuthenticatedAdminPaymentRequestsRouteImport } from './routes/_authenticated/admin.payment-requests'
import { Route as AuthenticatedAdminLessonsRouteImport } from './routes/_authenticated/admin.lessons'
import { Route as AuthenticatedAdminExamTemplatesRouteImport } from './routes/_authenticated/admin.exam-templates'
import { Route as AuthenticatedAdminAcademicRouteImport } from './routes/_authenticated/admin.academic'
import { Route as AuthenticatedUnitsUnitIdPracticeRouteImport } from './routes/_authenticated/units.$unitId.practice'
import { Route as AuthenticatedGradesGradeIdSubjectsRouteImport } from './routes/_authenticated/grades.$gradeId.subjects'
import { Route as AuthenticatedExamsTrainingTemplateIdRouteImport } from './routes/_authenticated/exams.training.$templateId'
import { Route as AuthenticatedExamsStrictTemplateIdRouteImport } from './routes/_authenticated/exams.strict.$templateId'
import { Route as AuthenticatedExamsHistorySessionIdRouteImport } from './routes/_authenticated/exams.history.$sessionId'
import { Route as AuthenticatedAdminLessonsLessonIdRouteImport } from './routes/_authenticated/admin.lessons.$lessonId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGradesRoute = AuthenticatedGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubjectsSubjectIdRoute =
  AuthenticatedSubjectsSubjectIdRouteImport.update({
    id: '/subjects/$subjectId',
    path: '/subjects/$subjectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsNewRoute =
  AuthenticatedPaymentsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedPaymentsRoute,
  } as any)
const AuthenticatedLessonsLessonIdRoute =
  AuthenticatedLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamsHistoryRoute =
  AuthenticatedExamsHistoryRouteImport.update({
    id: '/exams/history',
    path: '/exams/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUnitsRoute = AuthenticatedAdminUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSubjectsRoute =
  AuthenticatedAdminSubjectsRouteImport.update({
    id: '/subjects',
    path: '/subjects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQuestionsRoute =
  AuthenticatedAdminQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentRequestsRoute =
  AuthenticatedAdminPaymentRequestsRouteImport.update({
    id: '/payment-requests',
    path: '/payment-requests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLessonsRoute =
  AuthenticatedAdminLessonsRouteImport.update({
    id: '/lessons',
    path: '/lessons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExamTemplatesRoute =
  AuthenticatedAdminExamTemplatesRouteImport.update({
    id: '/exam-templates',
    path: '/exam-templates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAcademicRoute =
  AuthenticatedAdminAcademicRouteImport.update({
    id: '/academic',
    path: '/academic',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedUnitsUnitIdPracticeRoute =
  AuthenticatedUnitsUnitIdPracticeRouteImport.update({
    id: '/units/$unitId/practice',
    path: '/units/$unitId/practice',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGradesGradeIdSubjectsRoute =
  AuthenticatedGradesGradeIdSubjectsRouteImport.update({
    id: '/$gradeId/subjects',
    path: '/$gradeId/subjects',
    getParentRoute: () => AuthenticatedGradesRoute,
  } as any)
const AuthenticatedExamsTrainingTemplateIdRoute =
  AuthenticatedExamsTrainingTemplateIdRouteImport.update({
    id: '/exams/training/$templateId',
    path: '/exams/training/$templateId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamsStrictTemplateIdRoute =
  AuthenticatedExamsStrictTemplateIdRouteImport.update({
    id: '/exams/strict/$templateId',
    path: '/exams/strict/$templateId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamsHistorySessionIdRoute =
  AuthenticatedExamsHistorySessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => AuthenticatedExamsHistoryRoute,
  } as any)
const AuthenticatedAdminLessonsLessonIdRoute =
  AuthenticatedAdminLessonsLessonIdRouteImport.update({
    id: '/$lessonId',
    path: '/$lessonId',
    getParentRoute: () => AuthenticatedAdminLessonsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/contact': typeof ContactRoute
  '/data-deletion': typeof DataDeletionRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/grades': typeof AuthenticatedGradesRouteWithChildren
  '/payments': typeof AuthenticatedPaymentsRouteWithChildren
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/academic': typeof AuthenticatedAdminAcademicRoute
  '/admin/exam-templates': typeof AuthenticatedAdminExamTemplatesRoute
  '/admin/lessons': typeof AuthenticatedAdminLessonsRouteWithChildren
  '/admin/payment-requests': typeof AuthenticatedAdminPaymentRequestsRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/admin/units': typeof AuthenticatedAdminUnitsRoute
  '/exams/history': typeof AuthenticatedExamsHistoryRouteWithChildren
  '/lessons/$lessonId': typeof AuthenticatedLessonsLessonIdRoute
  '/payments/new': typeof AuthenticatedPaymentsNewRoute
  '/subjects/$subjectId': typeof AuthenticatedSubjectsSubjectIdRoute
  '/admin/lessons/$lessonId': typeof AuthenticatedAdminLessonsLessonIdRoute
  '/exams/history/$sessionId': typeof AuthenticatedExamsHistorySessionIdRoute
  '/exams/strict/$templateId': typeof AuthenticatedExamsStrictTemplateIdRoute
  '/exams/training/$templateId': typeof AuthenticatedExamsTrainingTemplateIdRoute
  '/grades/$gradeId/subjects': typeof AuthenticatedGradesGradeIdSubjectsRoute
  '/units/$unitId/practice': typeof AuthenticatedUnitsUnitIdPracticeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/contact': typeof ContactRoute
  '/data-deletion': typeof DataDeletionRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/grades': typeof AuthenticatedGradesRouteWithChildren
  '/payments': typeof AuthenticatedPaymentsRouteWithChildren
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/academic': typeof AuthenticatedAdminAcademicRoute
  '/admin/exam-templates': typeof AuthenticatedAdminExamTemplatesRoute
  '/admin/lessons': typeof AuthenticatedAdminLessonsRouteWithChildren
  '/admin/payment-requests': typeof AuthenticatedAdminPaymentRequestsRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/admin/units': typeof AuthenticatedAdminUnitsRoute
  '/exams/history': typeof AuthenticatedExamsHistoryRouteWithChildren
  '/lessons/$lessonId': typeof AuthenticatedLessonsLessonIdRoute
  '/payments/new': typeof AuthenticatedPaymentsNewRoute
  '/subjects/$subjectId': typeof AuthenticatedSubjectsSubjectIdRoute
  '/admin/lessons/$lessonId': typeof AuthenticatedAdminLessonsLessonIdRoute
  '/exams/history/$sessionId': typeof AuthenticatedExamsHistorySessionIdRoute
  '/exams/strict/$templateId': typeof AuthenticatedExamsStrictTemplateIdRoute
  '/exams/training/$templateId': typeof AuthenticatedExamsTrainingTemplateIdRoute
  '/grades/$gradeId/subjects': typeof AuthenticatedGradesGradeIdSubjectsRoute
  '/units/$unitId/practice': typeof AuthenticatedUnitsUnitIdPracticeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/contact': typeof ContactRoute
  '/data-deletion': typeof DataDeletionRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/grades': typeof AuthenticatedGradesRouteWithChildren
  '/_authenticated/payments': typeof AuthenticatedPaymentsRouteWithChildren
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/admin/academic': typeof AuthenticatedAdminAcademicRoute
  '/_authenticated/admin/exam-templates': typeof AuthenticatedAdminExamTemplatesRoute
  '/_authenticated/admin/lessons': typeof AuthenticatedAdminLessonsRouteWithChildren
  '/_authenticated/admin/payment-requests': typeof AuthenticatedAdminPaymentRequestsRoute
  '/_authenticated/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/_authenticated/admin/units': typeof AuthenticatedAdminUnitsRoute
  '/_authenticated/exams/history': typeof AuthenticatedExamsHistoryRouteWithChildren
  '/_authenticated/lessons/$lessonId': typeof AuthenticatedLessonsLessonIdRoute
  '/_authenticated/payments/new': typeof AuthenticatedPaymentsNewRoute
  '/_authenticated/subjects/$subjectId': typeof AuthenticatedSubjectsSubjectIdRoute
  '/_authenticated/admin/lessons/$lessonId': typeof AuthenticatedAdminLessonsLessonIdRoute
  '/_authenticated/exams/history/$sessionId': typeof AuthenticatedExamsHistorySessionIdRoute
  '/_authenticated/exams/strict/$templateId': typeof AuthenticatedExamsStrictTemplateIdRoute
  '/_authenticated/exams/training/$templateId': typeof AuthenticatedExamsTrainingTemplateIdRoute
  '/_authenticated/grades/$gradeId/subjects': typeof AuthenticatedGradesGradeIdSubjectsRoute
  '/_authenticated/units/$unitId/practice': typeof AuthenticatedUnitsUnitIdPracticeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/complete-profile'
    | '/contact'
    | '/data-deletion'
    | '/forgot-password'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/app'
    | '/grades'
    | '/payments'
    | '/subscription'
    | '/wallet'
    | '/auth/callback'
    | '/admin/academic'
    | '/admin/exam-templates'
    | '/admin/lessons'
    | '/admin/payment-requests'
    | '/admin/questions'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/units'
    | '/exams/history'
    | '/lessons/$lessonId'
    | '/payments/new'
    | '/subjects/$subjectId'
    | '/admin/lessons/$lessonId'
    | '/exams/history/$sessionId'
    | '/exams/strict/$templateId'
    | '/exams/training/$templateId'
    | '/grades/$gradeId/subjects'
    | '/units/$unitId/practice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/complete-profile'
    | '/contact'
    | '/data-deletion'
    | '/forgot-password'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/app'
    | '/grades'
    | '/payments'
    | '/subscription'
    | '/wallet'
    | '/auth/callback'
    | '/admin/academic'
    | '/admin/exam-templates'
    | '/admin/lessons'
    | '/admin/payment-requests'
    | '/admin/questions'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/units'
    | '/exams/history'
    | '/lessons/$lessonId'
    | '/payments/new'
    | '/subjects/$subjectId'
    | '/admin/lessons/$lessonId'
    | '/exams/history/$sessionId'
    | '/exams/strict/$templateId'
    | '/exams/training/$templateId'
    | '/grades/$gradeId/subjects'
    | '/units/$unitId/practice'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/complete-profile'
    | '/contact'
    | '/data-deletion'
    | '/forgot-password'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/grades'
    | '/_authenticated/payments'
    | '/_authenticated/subscription'
    | '/_authenticated/wallet'
    | '/auth/callback'
    | '/_authenticated/admin/academic'
    | '/_authenticated/admin/exam-templates'
    | '/_authenticated/admin/lessons'
    | '/_authenticated/admin/payment-requests'
    | '/_authenticated/admin/questions'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/subjects'
    | '/_authenticated/admin/units'
    | '/_authenticated/exams/history'
    | '/_authenticated/lessons/$lessonId'
    | '/_authenticated/payments/new'
    | '/_authenticated/subjects/$subjectId'
    | '/_authenticated/admin/lessons/$lessonId'
    | '/_authenticated/exams/history/$sessionId'
    | '/_authenticated/exams/strict/$templateId'
    | '/_authenticated/exams/training/$templateId'
    | '/_authenticated/grades/$gradeId/subjects'
    | '/_authenticated/units/$unitId/practice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  CompleteProfileRoute: typeof CompleteProfileRoute
  ContactRoute: typeof ContactRoute
  DataDeletionRoute: typeof DataDeletionRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grades': {
      id: '/_authenticated/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof AuthenticatedGradesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subjects/$subjectId': {
      id: '/_authenticated/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId'
      preLoaderRoute: typeof AuthenticatedSubjectsSubjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments/new': {
      id: '/_authenticated/payments/new'
      path: '/new'
      fullPath: '/payments/new'
      preLoaderRoute: typeof AuthenticatedPaymentsNewRouteImport
      parentRoute: typeof AuthenticatedPaymentsRoute
    }
    '/_authenticated/lessons/$lessonId': {
      id: '/_authenticated/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof AuthenticatedLessonsLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/history': {
      id: '/_authenticated/exams/history'
      path: '/exams/history'
      fullPath: '/exams/history'
      preLoaderRoute: typeof AuthenticatedExamsHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/units': {
      id: '/_authenticated/admin/units'
      path: '/units'
      fullPath: '/admin/units'
      preLoaderRoute: typeof AuthenticatedAdminUnitsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/subjects': {
      id: '/_authenticated/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AuthenticatedAdminSubjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/questions': {
      id: '/_authenticated/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AuthenticatedAdminQuestionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payment-requests': {
      id: '/_authenticated/admin/payment-requests'
      path: '/payment-requests'
      fullPath: '/admin/payment-requests'
      preLoaderRoute: typeof AuthenticatedAdminPaymentRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/lessons': {
      id: '/_authenticated/admin/lessons'
      path: '/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof AuthenticatedAdminLessonsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/exam-templates': {
      id: '/_authenticated/admin/exam-templates'
      path: '/exam-templates'
      fullPath: '/admin/exam-templates'
      preLoaderRoute: typeof AuthenticatedAdminExamTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/academic': {
      id: '/_authenticated/admin/academic'
      path: '/academic'
      fullPath: '/admin/academic'
      preLoaderRoute: typeof AuthenticatedAdminAcademicRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/units/$unitId/practice': {
      id: '/_authenticated/units/$unitId/practice'
      path: '/units/$unitId/practice'
      fullPath: '/units/$unitId/practice'
      preLoaderRoute: typeof AuthenticatedUnitsUnitIdPracticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grades/$gradeId/subjects': {
      id: '/_authenticated/grades/$gradeId/subjects'
      path: '/$gradeId/subjects'
      fullPath: '/grades/$gradeId/subjects'
      preLoaderRoute: typeof AuthenticatedGradesGradeIdSubjectsRouteImport
      parentRoute: typeof AuthenticatedGradesRoute
    }
    '/_authenticated/exams/training/$templateId': {
      id: '/_authenticated/exams/training/$templateId'
      path: '/exams/training/$templateId'
      fullPath: '/exams/training/$templateId'
      preLoaderRoute: typeof AuthenticatedExamsTrainingTemplateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/strict/$templateId': {
      id: '/_authenticated/exams/strict/$templateId'
      path: '/exams/strict/$templateId'
      fullPath: '/exams/strict/$templateId'
      preLoaderRoute: typeof AuthenticatedExamsStrictTemplateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/history/$sessionId': {
      id: '/_authenticated/exams/history/$sessionId'
      path: '/$sessionId'
      fullPath: '/exams/history/$sessionId'
      preLoaderRoute: typeof AuthenticatedExamsHistorySessionIdRouteImport
      parentRoute: typeof AuthenticatedExamsHistoryRoute
    }
    '/_authenticated/admin/lessons/$lessonId': {
      id: '/_authenticated/admin/lessons/$lessonId'
      path: '/$lessonId'
      fullPath: '/admin/lessons/$lessonId'
      preLoaderRoute: typeof AuthenticatedAdminLessonsLessonIdRouteImport
      parentRoute: typeof AuthenticatedAdminLessonsRoute
    }
  }
}

interface AuthenticatedAdminLessonsRouteChildren {
  AuthenticatedAdminLessonsLessonIdRoute: typeof AuthenticatedAdminLessonsLessonIdRoute
}

const AuthenticatedAdminLessonsRouteChildren: AuthenticatedAdminLessonsRouteChildren =
  {
    AuthenticatedAdminLessonsLessonIdRoute:
      AuthenticatedAdminLessonsLessonIdRoute,
  }

const AuthenticatedAdminLessonsRouteWithChildren =
  AuthenticatedAdminLessonsRoute._addFileChildren(
    AuthenticatedAdminLessonsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAcademicRoute: typeof AuthenticatedAdminAcademicRoute
  AuthenticatedAdminExamTemplatesRoute: typeof AuthenticatedAdminExamTemplatesRoute
  AuthenticatedAdminLessonsRoute: typeof AuthenticatedAdminLessonsRouteWithChildren
  AuthenticatedAdminPaymentRequestsRoute: typeof AuthenticatedAdminPaymentRequestsRoute
  AuthenticatedAdminQuestionsRoute: typeof AuthenticatedAdminQuestionsRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminSubjectsRoute: typeof AuthenticatedAdminSubjectsRoute
  AuthenticatedAdminUnitsRoute: typeof AuthenticatedAdminUnitsRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAcademicRoute: AuthenticatedAdminAcademicRoute,
  AuthenticatedAdminExamTemplatesRoute: AuthenticatedAdminExamTemplatesRoute,
  AuthenticatedAdminLessonsRoute: AuthenticatedAdminLessonsRouteWithChildren,
  AuthenticatedAdminPaymentRequestsRoute:
    AuthenticatedAdminPaymentRequestsRoute,
  AuthenticatedAdminQuestionsRoute: AuthenticatedAdminQuestionsRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
  AuthenticatedAdminSubjectsRoute: AuthenticatedAdminSubjectsRoute,
  AuthenticatedAdminUnitsRoute: AuthenticatedAdminUnitsRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedGradesRouteChildren {
  AuthenticatedGradesGradeIdSubjectsRoute: typeof AuthenticatedGradesGradeIdSubjectsRoute
}

const AuthenticatedGradesRouteChildren: AuthenticatedGradesRouteChildren = {
  AuthenticatedGradesGradeIdSubjectsRoute:
    AuthenticatedGradesGradeIdSubjectsRoute,
}

const AuthenticatedGradesRouteWithChildren =
  AuthenticatedGradesRoute._addFileChildren(AuthenticatedGradesRouteChildren)

interface AuthenticatedPaymentsRouteChildren {
  AuthenticatedPaymentsNewRoute: typeof AuthenticatedPaymentsNewRoute
}

const AuthenticatedPaymentsRouteChildren: AuthenticatedPaymentsRouteChildren = {
  AuthenticatedPaymentsNewRoute: AuthenticatedPaymentsNewRoute,
}

const AuthenticatedPaymentsRouteWithChildren =
  AuthenticatedPaymentsRoute._addFileChildren(
    AuthenticatedPaymentsRouteChildren,
  )

interface AuthenticatedExamsHistoryRouteChildren {
  AuthenticatedExamsHistorySessionIdRoute: typeof AuthenticatedExamsHistorySessionIdRoute
}

const AuthenticatedExamsHistoryRouteChildren: AuthenticatedExamsHistoryRouteChildren =
  {
    AuthenticatedExamsHistorySessionIdRoute:
      AuthenticatedExamsHistorySessionIdRoute,
  }

const AuthenticatedExamsHistoryRouteWithChildren =
  AuthenticatedExamsHistoryRoute._addFileChildren(
    AuthenticatedExamsHistoryRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedGradesRoute: typeof AuthenticatedGradesRouteWithChildren
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRouteWithChildren
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedExamsHistoryRoute: typeof AuthenticatedExamsHistoryRouteWithChildren
  AuthenticatedLessonsLessonIdRoute: typeof AuthenticatedLessonsLessonIdRoute
  AuthenticatedSubjectsSubjectIdRoute: typeof AuthenticatedSubjectsSubjectIdRoute
  AuthenticatedExamsStrictTemplateIdRoute: typeof AuthenticatedExamsStrictTemplateIdRoute
  AuthenticatedExamsTrainingTemplateIdRoute: typeof AuthenticatedExamsTrainingTemplateIdRoute
  AuthenticatedUnitsUnitIdPracticeRoute: typeof AuthenticatedUnitsUnitIdPracticeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedGradesRoute: AuthenticatedGradesRouteWithChildren,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRouteWithChildren,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedExamsHistoryRoute: AuthenticatedExamsHistoryRouteWithChildren,
  AuthenticatedLessonsLessonIdRoute: AuthenticatedLessonsLessonIdRoute,
  AuthenticatedSubjectsSubjectIdRoute: AuthenticatedSubjectsSubjectIdRoute,
  AuthenticatedExamsStrictTemplateIdRoute:
    AuthenticatedExamsStrictTemplateIdRoute,
  AuthenticatedExamsTrainingTemplateIdRoute:
    AuthenticatedExamsTrainingTemplateIdRoute,
  AuthenticatedUnitsUnitIdPracticeRoute: AuthenticatedUnitsUnitIdPracticeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  CompleteProfileRoute: CompleteProfileRoute,
  ContactRoute: ContactRoute,
  DataDeletionRoute: DataDeletionRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
