-- Historical fresh-replay compatibility repair
-- CONTENT-STAFF-RBAC-BASELINE-MIGRATION-RECONCILIATION-22
--
-- Historical replay reconciliation.
-- Content-staff helpers, RLS policies, grants, and storage policies are
-- created by migration 20260703121000_content_manager_rbac_policies.sql
-- (introduced by commit eb0392e, 2026-07-03).
--
-- This file originally duplicated that CONTENT-MANAGER-RBAC-01A surface via
-- Lovable/gpt-engineer commit 5fd1a9c (2026-07-03) with identical functions,
-- REVOKE/GRANT execute privileges, CREATE POLICY names, commands, roles,
-- USING / WITH CHECK expressions, admin_get_lesson_media_urls, and storage
-- object policies — formatting/whitespace differences only. Fresh baseline
-- replay failed with:
--   SQLSTATE 42710 — policy "Content staff manage grades" for table "grades"
--   already exists
--
-- Pre-repair SHA-256 of this file:
--   5966098F6D18119CE454CA0849E43A36ABD7E6342E67AB48078C1EA1F510A789
-- Canonical creator SHA-256:
--   5C8035188769A816FFDA68CBCF9345F7F8F45B5B705BD2258AE36FD3E263EEAF
--
-- Duplicate CREATE POLICY inventory (all exact semantic duplicates of the
-- earlier migration; first failure stops replay at grades):
--   Content staff manage grades
--   Content staff manage subjects
--   Content staff manage lessons
--   Content staff manage questions
--   Content staff manage tracks
--   Content staff manage governorates
--   Content staff manage map
--   Content staff manage units
--   Content staff manage book contents
--   Content staff manage explanations
--   Content staff manage assessments
--   Content staff manage resources
--   Content staff manage assessment questions
--   Content staff manage simulations
--   Content staff manage summaries
--   Authenticated can read active templates
--   Content staff manage templates
--   Authenticated can read questions of active templates
--   Content staff manage template questions
--   Content staff manage import jobs
--   Content staff manage import errors
--   Content staff manage lesson files - select
--   Content staff manage lesson files - insert
--   Content staff manage lesson files - update
--   Content staff manage lesson files - delete
-- Plus duplicate CREATE OR REPLACE for is_full_admin, is_content_staff,
-- admin_get_lesson_media_urls and matching REVOKE/GRANT EXECUTE.
--
-- This migration intentionally performs only missing additive operations.
-- Audit found no unique additive DDL beyond the earlier migration, so
-- this version is intentionally a no-op documentation marker.
--
-- Timestamp and filename preserved. Do not delete this migration version
-- from the ledger; environments that already recorded 20260703204450
-- keep a stable version entry without re-executing CREATE POLICY.
--
-- Not a CREATE POLICY IF NOT EXISTS workaround: every policy was compared
-- object-by-object (name, table, command, role, USING, WITH CHECK, helpers)
-- before removing the duplicate CREATE statements. Authorization was not
-- widened.
