// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error("Unauthorized: Invalid token");
    }

    if (!data.claims.sub) {
      throw new Error("Unauthorized: No user ID found in token");
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);

/** Requires authenticated user with admin role (JWT + has_role RPC). */
export const requireAdminAuth = createMiddleware({ type: "function" })
  .middleware([requireSupabaseAuth])
  .server(async ({ next, context }) => {
    const { supabase, userId } = context as {
      supabase: import("@supabase/supabase-js").SupabaseClient<Database>;
      userId: string;
    };

    const { data: isAdmin, error } = await supabase.rpc("has_role", {
      _user_id: userId,
      _role: "admin",
    });

    if (error) {
      throw new Error("تعذر التحقق من صلاحيات الإدارة.");
    }

    if (!isAdmin) {
      throw new Error("غير مصرح — صلاحيات الإدارة مطلوبة.");
    }

    return next({
      context: {
        ...context,
        isFullAdmin: true,
        isContentStaff: true,
      },
    });
  });

export type ContentStaffAuthContext = {
  supabase: import("@supabase/supabase-js").SupabaseClient<Database>;
  userId: string;
  isFullAdmin: boolean;
  isContentStaff: boolean;
};

/** Requires authenticated user with admin or content_manager role. */
export const requireContentStaffAuth = createMiddleware({ type: "function" })
  .middleware([requireSupabaseAuth])
  .server(async ({ next, context }) => {
    const { supabase, userId } = context as {
      supabase: import("@supabase/supabase-js").SupabaseClient<Database>;
      userId: string;
    };

    const { data: isAdmin, error: adminErr } = await supabase.rpc("has_role", {
      _user_id: userId,
      _role: "admin",
    });

    if (adminErr) {
      throw new Error("تعذر التحقق من صلاحيات الإدارة.");
    }

    if (isAdmin) {
      return next({
        context: {
          ...context,
          isFullAdmin: true,
          isContentStaff: true,
        },
      });
    }

    const { data: isContentManager, error: cmErr } = await supabase.rpc("has_role", {
      _user_id: userId,
      _role: "content_manager",
    });

    if (cmErr) {
      throw new Error("تعذر التحقق من صلاحيات إدارة المحتوى.");
    }

    if (!isContentManager) {
      throw new Error("غير مصرح — صلاحيات إدارة المحتوى مطلوبة.");
    }

    return next({
      context: {
        ...context,
        isFullAdmin: false,
        isContentStaff: true,
      },
    });
  });
