import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";
import { PUBLIC_SUPABASE_PUBLISHABLE_KEY, PUBLIC_SUPABASE_URL } from "./public-config";

const ANDROID_BROWSER_CALLBACK_ORIGIN = "https://studentamkeen.com";
const ANDROID_BROWSER_CALLBACK_PATH = "/auth/mobile-callback";

/**
 * OAuth responses are normally consumed by the WebView that initiated them.
 * The Android HTTPS compatibility callback is the sole exception: it can open
 * in a Chrome Custom Tab, which must never create a second browser-only
 * session. The native deep-link handler completes that exchange in the app.
 */
export function shouldDetectSessionInUrl(url: URL): boolean {
  return !(
    url.origin === ANDROID_BROWSER_CALLBACK_ORIGIN &&
    url.pathname.replace(/\/+$/, "") === ANDROID_BROWSER_CALLBACK_PATH
  );
}

function createSupabaseClient() {
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL ||
    process.env.VITE_SUPABASE_URL ||
    process.env.SUPABASE_URL ||
    PUBLIC_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    process.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY ||
    PUBLIC_SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
      // exchangeCodeForSession() requires the verifier generated by PKCE.
      // Supabase's browser default is implicit, so this must be explicit.
      flowType: "pkce",
      detectSessionInUrl: shouldDetectSessionInUrl,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
