from __future__ import annotations
import base64, hashlib, html, json, re, shutil, zipfile
from pathlib import Path
from xml.etree import ElementTree as ET

ROOT=Path(__file__).resolve().parents[2]; RAW=ROOT/'.local-intake/chemistry-g12-iron/raw'
OUT=ROOT/'content-packages/chemistry-g12-iron-v3'; ASSETS=OUT/'assets'; PREVIEW=OUT/'preview'
FILES={'sanaa_textbook':'كتاب الكيمياء الصف ثالث ثانوي منهج صنعاء.pdf','aden_textbook':'كتاب الكيمياء الصف ثالث ثانوي منهج عدن.pdf','activity_book':'كتاب الكيمياء - الانشطة والتجارب العملية منهج صنعاء وعدن.pdf','official_lesson':'الدرس الرابع-الحديد (2).pdf','explanation':'شرح درس الحديد Fe.docx','summary':'الحديد – ملخص شامل ومنظم.docx','mindmap':'4.html','lab':'مختبر_تمكين_الكشف_عن_الحديد (2).html','unit_assessment':'تقويم الوحده الاولى (2).pdf','self_test':'درس الحديد_استيراد_أسئلة (1).xlsx','ministerial':'نماذج_ثالث_ثانوي_كيمياء_علمي_2022_عدن.pdf','mindmap_reference':'tamkeen_iron_mindmap_site_preview.html'}
CAPS=['officialBookContent','tamkeenExplanationHtml','lessonSummaryHtml','mindMapHtml','labExperimentHtml','officialBookQuestions','selfTest']
SRC={k:RAW/v for k,v in FILES.items()}

def sha(p):
 h=hashlib.sha256()
 with p.open('rb') as f:
  for c in iter(lambda:f.read(1048576),b''): h.update(c)
 return h.hexdigest()
def put(p,v,raw=False):
 p.parent.mkdir(parents=True,exist_ok=True);p.write_text(v if raw else json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def paras(p):
 ns={'w':'http://schemas.openxmlformats.org/wordprocessingml/2006/main'}
 with zipfile.ZipFile(p) as z:r=ET.fromstring(z.read('word/document.xml'))
 return [s for x in r.findall('.//w:body/w:p',ns) if (s:=''.join(t.text or '' for t in x.findall('.//w:t',ns)).strip())]

CSS='''<style>:root{--ink:#172033;--brand:#8b3d20;--paper:#fffdf8;--line:#e6d9c8}*{box-sizing:border-box}html{direction:rtl}body{margin:0;background:#f5f0e8;color:var(--ink);font-family:Segoe UI,Tahoma,Arial,sans-serif;line-height:1.9}main{width:min(100% - 24px,900px);margin:12px auto;background:var(--paper);padding:18px;border:1px solid var(--line);border-radius:16px;overflow-wrap:anywhere}h1,h2{color:var(--brand);line-height:1.35}h1{font-size:1.55rem}h2{font-size:1.25rem;border-bottom:1px solid var(--line);padding-bottom:6px}.formula,.equation{direction:ltr;text-align:center;font-family:Georgia,serif;font-size:1.08rem;overflow-wrap:anywhere}.tamkeen-label{display:inline-block;background:#f1dfc9;color:#6e2d18;padding:2px 9px;border-radius:99px}.note{background:#fff5dc;border-right:4px solid #d28b2c;padding:9px;margin:10px 0}table{display:block;max-width:100%;overflow-x:auto;border-collapse:collapse}th,td{border:1px solid var(--line);padding:6px;min-width:110px}details{border:1px solid var(--line);border-radius:12px;padding:8px;margin:8px 0;background:#fff}summary{cursor:pointer;font-weight:700;color:var(--brand)}img{max-width:100%;height:auto}@media(min-width:640px){main{padding:28px}}</style>'''

def html_doc(ps):
 out=[CSS,'<main dir="rtl"><span class="tamkeen-label">شرح تمكين</span>']
 for p in ps:
  e=html.escape(p)
  tag='h2' if re.match(r'^(الحديد|مقدمة|أولاً|ثانياً|ثالثاً|رابعاً|خامساً|سادساً|سابعاً|ثامناً|تاسعاً|عاشراً|خاتمة|ملخص|نشاط|الكشف)',p) else 'p'
  cls=' class="equation" dir="ltr"' if tag=='p' and any(x in p for x in ['Fe','CO','O₂','H₂','Cl₂','→','⇌']) else ''
  out.append(f'<{tag}{cls}>{e}</{tag}>')
 out.append('</main>');return '\n'.join(out)

def b(id, kind, page, printed, text, body, region=None, **extra):
 d={'id':id,'type':kind,'source_page':page,'printed_page':printed,'text':text,'html':body}
 if region:d['source_region']=region
 d.update(extra);return d

def formula(label, page, printed, text, body):
 return b(label,'equation',page,printed,text,f'<div class="equation" dir="ltr">{body}</div>')

def blocks(figure_sha):
 return [
  b('iron-family','table',1,14,'جدول (1-3) خواص عائلة الحديد','''<div class="table-scroll"><table><caption>جدول (1-3) خواص عائلة الحديد</caption><thead><tr><th rowspan="2">العنصر</th><th rowspan="2">رمز العنصر</th><th rowspan="2">التركيب الإلكتروني</th><th rowspan="2">الوزن الذري</th><th colspan="2">نصف القطر (Å)</th></tr><tr><th>الذري</th><th>الأيوني</th></tr></thead><tbody><tr><td>حديد</td><td><sup>26</sup>Fe</td><td>[Ar] 3d<sup>6</sup> 4s<sup>2</sup></td><td>55.85</td><td>1.16</td><td>0.76</td></tr><tr><td>كوبلت</td><td><sup>27</sup>Co</td><td>[Ar] 3d<sup>7</sup> 4s<sup>2</sup></td><td>58.62</td><td>1.16</td><td>0.74</td></tr><tr><td>نيكل</td><td><sup>28</sup>Ni</td><td>[Ar] 3d<sup>8</sup> 4s<sup>2</sup></td><td>58.71</td><td>1.15</td><td>0.72</td></tr></tbody></table></div>''',{'x0':66.0,'y0':54.0,'x1':494.0,'y1':190.0},columns=['العنصر','رمز العنصر','التركيب الإلكتروني','الوزن الذري','نصف القطر الذري (Å)','نصف القطر الأيوني (Å)'],units={'الوزن الذري':'وحدة كتلة ذرية','نصف القطر الذري (Å)':'Å','نصف القطر الأيوني (Å)':'Å'},rows=[['حديد','²⁶Fe','[Ar] 3d⁶ 4s²','55.85','1.16','0.76'],['كوبلت','²⁷Co','[Ar] 3d⁷ 4s²','58.62','1.16','0.74'],['نيكل','²⁸Ni','[Ar] 3d⁸ 4s²','58.71','1.15','0.72']]),
  b('lesson-heading','heading',1,14,'الحديد (Fe)','<h1>الحديد (Fe)</h1>'),
  b('intro','paragraph',1,14,'الحديد هو أكثر الفلزات الانتقالية استعمالاً، وذلك لوفرته النسبية وسهولة استخلاصه من خاماته، وفي حالته النقية نجد أنه ليس قاسياً جداً، ولكن عند إضافة كميات صغيرة من الكربون والفلزات الأخرى إليه تتكون سبائك الفولاذ القوية.','<p>الحديد هو أكثر الفلزات الانتقالية استعمالاً، وذلك لوفرته النسبية وسهولة استخلاصه من خاماته، وفي حالته النقية نجد أنه ليس قاسياً جداً، ولكن عند إضافة كميات صغيرة من الكربون والفلزات الأخرى إليه تتكون سبائك الفولاذ القوية.</p>'),
  b('ores-heading','heading',1,14,'خامات الحديد:','<h2>خامات الحديد:</h2>'),
  b('oxidation-and-oxides','paragraph',1,14,'لأن الحديد فلز فعّال نوعاً ما، ويكوّن مركبات بشكل رئيس في حالتي التأكسد (+2 و +3)، فهو يعمل على أكسدة مركبات الحديد (II) لتعطي مركبات الحديد (III) المقابلة لها. كما يكوّن الحديد ثلاثة أكاسيد هي: FeO و Fe₂O₃ و (FeO . Fe₂O₃). وأكسيد الحديد (II) صعب التحضير، ويتحول إلى: Fe و Fe₂O₃ عند تسخينه، كما توضحه المعادلة الآتية:','<p>لأن الحديد فلز فعّال نوعاً ما، ويكوّن مركبات بشكل رئيس في حالتي التأكسد (+2 و +3)، فهو يعمل على أكسدة مركبات الحديد (II) لتعطي مركبات الحديد (III) المقابلة لها. كما يكوّن الحديد ثلاثة أكاسيد هي: FeO و Fe<sub>2</sub>O<sub>3</sub> و (FeO . Fe<sub>2</sub>O<sub>3</sub>). وأكسيد الحديد (II) صعب التحضير، ويتحول إلى: Fe و Fe<sub>2</sub>O<sub>3</sub> عند تسخينه، كما توضحه المعادلة الآتية:</p>'),
  formula('iron-ii-decomposition',1,14,'3FeO(s) → Fe(s) + Fe₂O₃(s)','3FeO<sub>(s)</sub> → Fe<sub>(s)</sub> + Fe<sub>2</sub>O<sub>3(s)</sub>'),
  b('ores-intro','paragraph',1,14,'وتختلف خامات الحديد حسب تركيبها الكيميائي والمعدني، ومن أهمها:','<p>وتختلف خامات الحديد حسب تركيبها الكيميائي والمعدني، ومن أهمها:</p>'),
  b('magnetite','paragraph',1,14,'١- أكسيد الحديد المغناطيسي (Fe₃O₄): وهو خام لونه رمادي مائل للسواد ويسمى بالاسم المعروف الماجنيتايت Magnetite، وتكون نسبة الحديد عادةً من (40-70%)، وفي حالة تأكسدين مختلفين، وتكتب صيغته بالشكل (Feᴵᴵ, Feᴵᴵᴵ) للدلالة على حالات تأكسد الحديد، وكما يدل اسمه فإن الماجنيتايت مغناطيسي، وهو من خامات الحديد المهمة؛ لأنه من الممكن فصله بسهولة عن الصخور عديمة الفائدة بواسطة مغناطيس قوي؛ لأنه غني بالحديد.','<p>١- أكسيد الحديد المغناطيسي (Fe<sub>3</sub>O<sub>4</sub>): وهو خام لونه رمادي مائل للسواد ويسمى بالاسم المعروف الماجنيتايت Magnetite، وتكون نسبة الحديد عادةً من (40-70%)، وفي حالة تأكسدين مختلفين، وتكتب صيغته بالشكل (Fe<sup>II</sup>, Fe<sup>III</sup>) للدلالة على حالات تأكسد الحديد، وكما يدل اسمه فإن الماجنيتايت مغناطيسي، وهو من خامات الحديد المهمة؛ لأنه من الممكن فصله بسهولة عن الصخور عديمة الفائدة بواسطة مغناطيس قوي؛ لأنه غني بالحديد.</p>'),
  b('hematite','paragraph',2,15,'٢- أكسيد الحديد اللامائي: ويسمى أكسيد الحديد هنا بالهيماتيت، ويكون الحديد فيه على شكل أكسيد الحديد (III) الأحمر (Fe₂O₃). وتتراوح نسبة الحديد فيه ما بين 45-50%، واستخراج الحديد من هذا الأكسيد يعد اقتصادياً أكثر من استخراجه من الخامات الأخرى، مثل: الماجنيتايت؛ لأنه من السهل اختزال الخامات الحمراء منه.','<p>٢- أكسيد الحديد اللامائي: ويسمى أكسيد الحديد هنا بالهيماتيت، ويكون الحديد فيه على شكل أكسيد الحديد (III) الأحمر (Fe<sub>2</sub>O<sub>3</sub>). وتتراوح نسبة الحديد فيه ما بين 45-50%، واستخراج الحديد من هذا الأكسيد يعد اقتصادياً أكثر من استخراجه من الخامات الأخرى، مثل: الماجنيتايت؛ لأنه من السهل اختزال الخامات الحمراء منه.</p>'),
  b('limonite','paragraph',2,15,'٣- أكسيد الحديد المائي: ورمزه الكيميائي هو (Fe₂O₃.nH₂O)، حيث يحتوي هذا المركب على كمية من الماء، ويسمى (بالليمونيت) نسبة إلى لونه الأصفر، ويحتوي غالباً على 57.14% من فلز الحديد، و52.35% ماء، وهذا الأكسيد المميأ هو الصدأ (Rust).','<p>٣- أكسيد الحديد المائي: ورمزه الكيميائي هو (Fe<sub>2</sub>O<sub>3</sub>.nH<sub>2</sub>O)، حيث يحتوي هذا المركب على كمية من الماء، ويسمى (بالليمونيت) نسبة إلى لونه الأصفر، ويحتوي غالباً على 57.14% من فلز الحديد، و52.35% ماء، وهذا الأكسيد المميأ هو الصدأ (Rust).</p>'),
  b('other-ores','paragraph',2,15,'أما خامات الحديد الأخرى فيكون الحديد فيها قليلاً، إذ تتراوح نسبته فيها مابين 25-50%.','<p>أما خامات الحديد الأخرى فيكون الحديد فيها قليلاً، إذ تتراوح نسبته فيها مابين 25-50%.</p>'),
  b('mining-heading','heading',2,15,'تعدين الحديد:','<h2>تعدين الحديد:</h2>'),
  b('mining','paragraph',2,15,'يستخرج الحديد من خاماته وذلك عن طريق الاختزال، ولأن الحديد ينتج بكميات كبيرة، فإن المادة المختزلة يجب أن تكون رخيصة الثمن وأقل تكلفة. ومن أرخص هذه المواد الكربون (على شكل فحم الكوك) الذي ينتج من الفحم الحجري بعد تسخينه إلى درجات حرارة مرتفعة بمعزل عن الهواء. وتؤدي هذه المعالجة إلى طرد المواد المتطايرة الموجودة في الفحم الحجري (والتي يتم منها اشتقاق مواد كيميائية أخرى مهمة) مخلفة وراءها كربوناً نقياً إلى حد ما. وتتم عملية اختزال الحديد في الفرن العالي (اللافح) كما يأتي:','<p>يستخرج الحديد من خاماته وذلك عن طريق الاختزال، ولأن الحديد ينتج بكميات كبيرة، فإن المادة المختزلة يجب أن تكون رخيصة الثمن وأقل تكلفة. ومن أرخص هذه المواد الكربون (على شكل فحم الكوك) الذي ينتج من الفحم الحجري بعد تسخينه إلى درجات حرارة مرتفعة بمعزل عن الهواء. وتؤدي هذه المعالجة إلى طرد المواد المتطايرة الموجودة في الفحم الحجري (والتي يتم منها اشتقاق مواد كيميائية أخرى مهمة) مخلفة وراءها كربوناً نقياً إلى حد ما. وتتم عملية اختزال الحديد في الفرن العالي (اللافح) كما يأتي:</p>'),
  b('charge','paragraph',2,15,'- يضاف إلى الفرن مزيج من الخامات تسمى بالشحنة (Charge) والتي تتألف من حجر جيري وفحم الكوك وخام الحديد، الذي يحتوي غالباً على Fe₂O₃ مخلوطاً ببعض الشوائب مثل SiO₂ (أي رمل، حوالي 10%)، وكميات ضئيلة من مركبات أخرى تحتوي على الكبريت والفوسفور والألومنيوم والمنجنيز. وبعد ذلك يدفع إلى داخل الفرن هواء ساخن مضغوط أو أكسجين نقي، كما في شكل (1-1)، حيث يتفاعل الأكسجين مع الكربون منتجاً غاز ثاني أكسيد الكربون مصحوباً بحرارة عالية، حسب المعادلة الآتية:','<p>- يضاف إلى الفرن مزيج من الخامات تسمى بالشحنة (Charge) والتي تتألف من حجر جيري وفحم الكوك وخام الحديد، الذي يحتوي غالباً على Fe<sub>2</sub>O<sub>3</sub> مخلوطاً ببعض الشوائب مثل SiO<sub>2</sub> (أي رمل، حوالي 10%)، وكميات ضئيلة من مركبات أخرى تحتوي على الكبريت والفوسفور والألومنيوم والمنجنيز. وبعد ذلك يدفع إلى داخل الفرن هواء ساخن مضغوط أو أكسجين نقي، كما في شكل (1-1)، حيث يتفاعل الأكسجين مع الكربون منتجاً غاز ثاني أكسيد الكربون مصحوباً بحرارة عالية، حسب المعادلة الآتية:</p>'),
  formula('carbon-dioxide-formation',2,15,'C(s) + O₂(g) → CO₂(g)  ΔH= −394 Kj/mole','C<sub>(s)</sub> + O<sub>2(g)</sub> → CO<sub>2(g)</sub> &nbsp; ΔH= −394 Kj/mole'),
  b('hot-zone','paragraph',3,16,'- وتؤدي كمية الحرارة المرتفعة المتولدة في هذا القسم من الفرن إلى رفع درجة الحرارة إلى ما يقارب 1900°م، وفي أثناء تصاعد الغازات الساخنة يتفاعل CO₂ مع كميات إضافية من الكربون في تفاعل ماص للحرارة ليكون أول أكسيد الكربون الذي يعتبر عامل الاختزال الفعال في الفرن.','<p>- وتؤدي كمية الحرارة المرتفعة المتولدة في هذا القسم من الفرن إلى رفع درجة الحرارة إلى ما يقارب 1900°م، وفي أثناء تصاعد الغازات الساخنة يتفاعل CO<sub>2</sub> مع كميات إضافية من الكربون في تفاعل ماص للحرارة ليكون أول أكسيد الكربون الذي يعتبر عامل الاختزال الفعال في الفرن.</p>'),
  formula('carbon-monoxide-formation',3,16,'CO₂(g) + C(s) → 2CO(g)  ΔH= +173 Kj','CO<sub>2(g)</sub> + C<sub>(s)</sub> → 2CO<sub>(g)</sub> &nbsp; ΔH= +173 Kj'),
  b('furnace-figure','figure',3,16,'شكل (1-1) الفرن العالي (اللافح)','<figure><img src="assets/official-figure-1-1.png" alt="شكل (1-1) الفرن العالي (اللافح)"><figcaption>شكل (1-1) الفرن العالي (اللافح)</figcaption></figure>',{'x0':66.36,'y0':54.29,'x1':313.92,'y1':355.49},asset='assets/official-figure-1-1.png',asset_sha256='sha256:'+figure_sha,extraction='embedded source image; no redraw or montage'),
  b('reduction-intro','paragraph',3,16,'وتحدث عملية اختزال خام الحديد في سلسلة من الخطوات، انظر الشكل (1-1) تجد أنه بقرب قمة الفرن يتم اختزال Fe₂O₃ إلى Fe₃O₄، كما في المعادلة الآتية:','<p>وتحدث عملية اختزال خام الحديد في سلسلة من الخطوات، انظر الشكل (1-1) تجد أنه بقرب قمة الفرن يتم اختزال Fe<sub>2</sub>O<sub>3</sub> إلى Fe<sub>3</sub>O<sub>4</sub>، كما في المعادلة الآتية:</p>'),
  formula('hematite-reduction',3,16,'3Fe₂O₃ + CO → 2Fe₃O₄ + CO₂','3Fe<sub>2</sub>O<sub>3</sub> + CO → 2Fe<sub>3</sub>O<sub>4</sub> + CO<sub>2</sub>'),
  b('magnetite-reduction-intro','paragraph',3,16,'وإلى أسفل من ذلك بقليل، في منطقة أكثر حرارة من الفرن، يختزل Fe₃O₄ إلى FeO، حسب المعادلة الآتية:','<p>وإلى أسفل من ذلك بقليل، في منطقة أكثر حرارة من الفرن، يختزل Fe<sub>3</sub>O<sub>4</sub> إلى FeO، حسب المعادلة الآتية:</p>'),
  formula('magnetite-reduction',3,16,'Fe₃O₄ + CO → 3FeO + CO₂','Fe<sub>3</sub>O<sub>4</sub> + CO → 3FeO + CO<sub>2</sub>'),
  b('ferrous-reduction-intro','paragraph',3,16,'وأخيراً يختزل FeO إلى الفلز تحت المنطقة السابقة - أيضاً - ويكون الفلز عند درجات الحرارة العالية هذه سائلاً فينساب إلى الأسفل مكوناً بركة من الفلز المصهور في قاعدة البرج.','<p>وأخيراً يختزل FeO إلى الفلز تحت المنطقة السابقة - أيضاً - ويكون الفلز عند درجات الحرارة العالية هذه سائلاً فينساب إلى الأسفل مكوناً بركة من الفلز المصهور في قاعدة البرج.</p>'),
  formula('ferrous-reduction',3,16,'FeO + CO → Fe + CO₂','FeO + CO → Fe + CO<sub>2</sub>'),
  b('limestone-function','paragraph',3,16,'ووظيفة الحجر الجيري في الفرن تتمثل في تزويد وسط قاعدي تتفاعل معه الأكاسيد الحامضية، مثل: SiO₂ و P₂O₅، أو الأكاسيد الأمفوتيرية مثل Al₂O₃. فعند درجات الحرارة المرتفعة','<p>ووظيفة الحجر الجيري في الفرن تتمثل في تزويد وسط قاعدي تتفاعل معه الأكاسيد الحامضية، مثل: SiO<sub>2</sub> و P<sub>2</sub>O<sub>5</sub>، أو الأكاسيد الأمفوتيرية مثل Al<sub>2</sub>O<sub>3</sub>. فعند درجات الحرارة المرتفعة</p>'),
  b('limestone-decomposition-intro','paragraph',4,17,'الحرارة المرتفعة يتحلل الحجر الجيري CaCO₃ ليكون الجير (CaO) و CO₂، حسب المعادلة الآتية:','<p>الحرارة المرتفعة يتحلل الحجر الجيري CaCO<sub>3</sub> ليكون الجير (CaO) و CO<sub>2</sub>، حسب المعادلة الآتية:</p>'),
  formula('limestone-decomposition',4,17,'CaCO₃ → CaO + CO₂','CaCO<sub>3</sub> → CaO + CO<sub>2</sub>'),
  b('slag-heading','paragraph',4,17,'ويتفاعل بعد ذلك الجير، كالآتي:','<p>ويتفاعل بعد ذلك الجير، كالآتي:</p>'),
  formula('silicate-slag',4,17,'CaO + SiO₂ → CaSiO₃','CaO + SiO<sub>2</sub> → CaSiO<sub>3</sub>'),
  formula('phosphate-slag',4,17,'6CaO + 2P₂O₅ → 2Ca₃(PO₄)₂','6CaO + 2P<sub>2</sub>O<sub>5</sub> → 2Ca<sub>3</sub>(PO<sub>4</sub>)<sub>2</sub>'),
  formula('aluminate-slag',4,17,'CaO + Al₂O₃ → Ca(AlO₂)₂','CaO + Al<sub>2</sub>O<sub>3</sub> → Ca(AlO<sub>2</sub>)<sub>2</sub>'),
  b('slag-process','paragraph',4,17,'وللمواد الناتجة عن هذه التفاعلات درجات انصهار منخفضة وهي في الحالة السائلة عند تكوينها، ويتجه هذا المزيج والذي يسمى بالخبث (Slag) إلى قاعدة الفرن، حيث يطفو على سطح الحديد المصهور. وفي أثناء تكون هاتين الطبقتين تهبط الشحنة في الفرن، وعندها يتم وضع كميات إضافية من مزيج (الحجر الجيري، وخام الحديد، وفحم الكوك) من الفتحة العليا للفرن. وبهذه الطريقة يعمل الفرن العالي (اللافح) باستمرار عن طريق إضافة شحنة من الأعلى وسحب الحديد المصهور والخبث من الأسفل، ويتم عادة تشغيل هذه الأفران لمدة شهور في كل مرة قبل إيقافها لأغراض الصيانة الروتينية. ويسمى الحديد السائل الذي يتم سحبه من الفرن العالي بالحديد الفضي، ويتكون من حوالي 95% حديد، وما يقارب 4% من الكربون، مع بعض الكميات الضئيلة من: السيليكون، والمنجنيز، والفوسفور، والكبريت. وهذا الحديد الناتج يعد صلباً جداً، ويمكن صبه في قوالب صب (Cast Iron)، أما الخَبَث فيمكن استعماله في صناعة الإسمنت.','<p>وللمواد الناتجة عن هذه التفاعلات درجات انصهار منخفضة وهي في الحالة السائلة عند تكوينها، ويتجه هذا المزيج والذي يسمى بالخبث (Slag) إلى قاعدة الفرن، حيث يطفو على سطح الحديد المصهور. وفي أثناء تكون هاتين الطبقتين تهبط الشحنة في الفرن، وعندها يتم وضع كميات إضافية من مزيج (الحجر الجيري، وخام الحديد، وفحم الكوك) من الفتحة العليا للفرن. وبهذه الطريقة يعمل الفرن العالي (اللافح) باستمرار عن طريق إضافة شحنة من الأعلى وسحب الحديد المصهور والخبث من الأسفل، ويتم عادة تشغيل هذه الأفران لمدة شهور في كل مرة قبل إيقافها لأغراض الصيانة الروتينية. ويسمى الحديد السائل الذي يتم سحبه من الفرن العالي بالحديد الفضي، ويتكون من حوالي 95% حديد، وما يقارب 4% من الكربون، مع بعض الكميات الضئيلة من: السيليكون، والمنجنيز، والفوسفور، والكبريت. وهذا الحديد الناتج يعد صلباً جداً، ويمكن صبه في قوالب صب (Cast Iron)، أما الخَبَث فيمكن استعماله في صناعة الإسمنت.</p>'),
  b('properties-heading','heading',4,17,'خواص الحديد:','<h2>خواص الحديد:</h2>'),
  b('physical-properties','paragraph',4,17,'الحديد النقي في حالته الصلبة عبارة عن فلز فضي أبيض اللون، لين، قابل للطرق وكثافته عند درجة 20°م تساوي 7.874 جم/سم³، ودرجة انصهاره 1535°م، ودرجة غليانه 2750°م، وعند انصهار الحديد يزداد حجمه بمقدار 4.4%.','<p>الحديد النقي في حالته الصلبة عبارة عن فلز فضي أبيض اللون، لين، قابل للطرق وكثافته عند درجة 20°م تساوي 7.874 جم/سم<sup>3</sup>، ودرجة انصهاره 1535°م، ودرجة غليانه 2750°م، وعند انصهار الحديد يزداد حجمه بمقدار 4.4%.</p>'),
  b('physical-properties-followup','paragraph',4,17,'ويعتبر الحديد من المواد المختزلة الجيدة، كما أنه يعد موصلاً جيداً للحرارة والكهرباء، ومسحوق الحديد أسود وغالباً ما يتوفر في المعامل المدرسية باسم برادة الحديد.','<p>ويعتبر الحديد من المواد المختزلة الجيدة، كما أنه يعد موصلاً جيداً للحرارة والكهرباء، ومسحوق الحديد أسود وغالباً ما يتوفر في المعامل المدرسية باسم برادة الحديد.</p>'),
  b('reactions-heading','heading',5,18,'ومن أهم تفاعلات الحديد ما يلي:','<h2>ومن أهم تفاعلات الحديد ما يلي:</h2>'),
  b('oxygen-water-intro','paragraph',5,18,'١- عند تسخين الحديد لدرجة الاحمرار فإنه يتفاعل مع الأكسجين، وكذلك مع بخار الماء مكوناً أكسيد الحديد المغناطيسي.','<p>١- عند تسخين الحديد لدرجة الاحمرار فإنه يتفاعل مع الأكسجين، وكذلك مع بخار الماء مكوناً أكسيد الحديد المغناطيسي.</p>'),
  formula('oxygen',5,18,'3Fe + 2O₂ → Fe₃O₄','3Fe + 2O<sub>2</sub> <span class="condition">Δ</span>→ Fe<sub>3</sub>O<sub>4</sub>'),
  formula('steam',5,18,'3Fe + 4H₂O(g) → Fe₃O₄ + 4H₂↑','3Fe + 4H<sub>2</sub>O<sub>(g)</sub> <span class="condition">Δ</span>→ Fe<sub>3</sub>O<sub>4</sub> + 4H<sub>2</sub>↑'),
  b('rust-intro','paragraph',5,18,'٢- يتفاعل الحديد مع الهواء الرطب مكوناً طبقة من الصدأ، وهي طبقة هشة مسامية غير قادرة على وقاية الحديد من مواصلة التآكل، ولذلك لا بد من حماية الحديد من التآكل، والتفاعل الإجمالي لتكوين الصدأ هو:','<p>٢- يتفاعل الحديد مع الهواء الرطب مكوناً طبقة من الصدأ، وهي طبقة هشة مسامية غير قادرة على وقاية الحديد من مواصلة التآكل، ولذلك لا بد من حماية الحديد من التآكل، والتفاعل الإجمالي لتكوين الصدأ هو:</p>'),
  formula('rust-equation',5,18,'4Fe + 2H₂O + 3O₂ → 2(Fe₂O₃ . H₂O)','4Fe + 2H<sub>2</sub>O + 3O<sub>2</sub> → 2(Fe<sub>2</sub>O<sub>3</sub> . H<sub>2</sub>O)'),
  b('nonmetal-intro','paragraph',5,18,'٣- يتحد الحديد مع كثير من اللافلزات في درجات الحرارة العالية، فمثلاً يكون مع الكلور كلوريد الحديد (III)، ومع الكبريت كبريتيد الحديد (II):','<p>٣- يتحد الحديد مع كثير من اللافلزات في درجات الحرارة العالية، فمثلاً يكون مع الكلور كلوريد الحديد (III)، ومع الكبريت كبريتيد الحديد (II):</p>'),
  formula('chlorine',5,18,'2Fe + 3Cl₂ → 2FeCl₃','2Fe + 3Cl<sub>2</sub> <span class="condition">Δ</span>→ 2FeCl<sub>3</sub>'),
  formula('sulfur',5,18,'Fe + S → FeS','Fe + S <span class="condition">Δ</span>→ FeS'),
  b('acids-intro','paragraph',5,18,'٤- يتفاعل الحديد مع حمض الهيدروكلوريك المخفف أو المركز، وحمض الكبريتيك المخفف ليعطي أملاح الحديد المطابقة وغاز الهيدروجين.','<p>٤- يتفاعل الحديد مع حمض الهيدروكلوريك المخفف أو المركز، وحمض الكبريتيك المخفف ليعطي أملاح الحديد المطابقة وغاز الهيدروجين.</p>'),
  formula('hydrochloric-acid',5,18,'Fe + 2HCl → FeCl₂ + H₂↑','Fe + 2HCl → FeCl<sub>2</sub> + H<sub>2</sub>↑'),
  formula('sulfuric-acid',5,18,'Fe + H₂SO₄ → FeSO₄ + H₂↑','Fe + H<sub>2</sub>SO<sub>4</sub> → FeSO<sub>4</sub> + H<sub>2</sub>↑'),
  b('passivation','note',5,18,'ملاحظة: لا يتأثر الحديد بحمض الكبريتيك وحمض النيتريك المركزين، ويرجع ذلك لتكوين طبقة رقيقة من أكسيد الحديد المغناطيسي (Fe₃O₄)، وهذه الطبقة تحمي فلز الحديد وتحول دون تفاعله.','<aside class="note"><strong>ملاحظة</strong><p>لا يتأثر الحديد بحمض الكبريتيك وحمض النيتريك المركزين، ويرجع ذلك لتكوين طبقة رقيقة من أكسيد الحديد المغناطيسي (Fe<sub>3</sub>O<sub>4</sub>)، وهذه الطبقة تحمي فلز الحديد وتحول دون تفاعله.</p></aside>'),
  b('activity-caption','caption',5,18,'نشاط (1-1)','<h3>نشاط (1-1)</h3>'),
  b('activity','activity',5,18,'الكشف عن الحديد في أملاحه: قم بتنفيذ التجارب الخاصة بالكشف عن الحديد في أملاحه في كتاب الأنشطة والتجارب العملية المرفق بهذا الكتاب.','<aside class="activity"><strong>الكشف عن الحديد في أملاحه:</strong> قم بتنفيذ التجارب الخاصة بالكشف عن الحديد في أملاحه في كتاب الأنشطة والتجارب العملية المرفق بهذا الكتاب.</aside>')
 ]

def official_html(bs,h):
 return f'<section id="officialBookContent" data-layer="A_OFFICIAL_TEXTBOOK" data-official-standard="20A" dir="rtl" data-source-file-hash="sha256:{h}">'+''.join(f'<section data-block-id="{b["id"]}" data-block-type="{b["type"]}" data-source-page="{b["source_page"]}" data-printed-page="{b["printed_page"]}">{b["html"]}</section>' for b in bs)+'</section>'

def mindmap():
 return CSS+'''<main dir="rtl"><span class="tamkeen-label">خريطة ذهنية تمكين</span><h1>الحديد Fe</h1><details open><summary>عنصر الحديد Fe</summary><details><summary>أهم خامات الحديد</summary><ul><li>الماجنيتيت Fe3O4</li><li>الهيماتيت Fe2O3</li><li>الليمونيت Fe2O3.nH2O</li></ul></details><details><summary>تعدين واستخلاص الحديد</summary><details><summary>الفرن العالي اللافح</summary><ul><li>استخدام فحم الكوك كعامل مختزل</li><li>إضافة الحجر الجيري للتخلص من الشوائب</li><li>إنتاج الحديد الغفل بنسبة نقاء عالية</li></ul><details><summary>التفاعلات الكيميائية بالفرن</summary><ul><li>تكوين أول أكسيد الكربون CO</li><li>اختزال أكاسيد الحديد إلى Fe</li><li>تكوين الخبث السائل Slag</li></ul></details></details></details><details><summary>خواص الحديد وتفاعلاته</summary><details><summary>الخواص الفيزيائية</summary><ul><li>فلز فضي لين قابل للطرق</li><li>الانصهار عند 1535 درجة مئوية</li><li>توصيل جيد للحرارة والكهرباء</li></ul></details><details><summary>التفاعلات الكيميائية</summary><ul><li>التفاعل مع O2 وبخار الماء لتكوين Fe3O4</li><li>تكوين الصدأ Rust في الهواء الرطب</li><li>التفاعل مع Cl2 لتكوين FeCl3</li><li>التفاعل مع الأحماض لإنتاج H2 وأملاح الحديد</li></ul></details></details></details></main>'''

def lab():
 js='''const bridge=window.__TasheelBridge;function logEvent(type,payload){if(bridge&&typeof bridge.sendInteraction==="function")bridge.sendInteraction({type,payload});}function showResult(){const ion=document.querySelector("#ion").value;const box=document.querySelector("#result");const data=ion==="Fe2+"?{name:"Fe(OH)2",color:"أبيض مخضر",eq:"Fe²⁺(aq)+2OH⁻(aq)→Fe(OH)₂(s)"}:{name:"Fe(OH)3",color:"بني محمر",eq:"Fe³⁺(aq)+3OH⁻(aq)→Fe(OH)₃(s)"};box.innerHTML="<strong>الملاحظة:</strong> يتكون راسب "+data.name+" "+data.color+"<p dir=\\"ltr\\">"+data.eq+"</p>";logEvent("iron-test-result",data);}document.addEventListener("DOMContentLoaded",()=>{document.querySelector("#run").addEventListener("click",showResult);if(bridge&&typeof bridge.markStarted==="function")bridge.markStarted({capability:"labExperimentHtml"});});'''
 digest=base64.b64encode(hashlib.sha256(js.encode()).digest()).decode()
 return '<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src \'none\';style-src \'unsafe-inline\';script-src \'self\' \'sha256-'+digest+'\';img-src \'self\' data:;connect-src \'none\'"><style>body{margin:0;background:#f8f3ea;color:#172033;font-family:Segoe UI,Tahoma,Arial,sans-serif;line-height:1.8}main{max-width:720px;margin:auto;padding:16px}button,select{font:inherit;padding:8px;margin:4px;border:1px solid #b98b67;border-radius:8px;background:#fff}#result{margin-top:12px;padding:12px;background:#fff7dc;border-right:4px solid #b46a22}.model{font-size:.9rem;color:#6e2d18}</style></head><body><main><h1>الكشف عن الحديد في أملاحه</h1><p>اختر أيون الحديد ثم أضف الكاشف لعرض الملاحظة.</p><label for="ion">الأيون</label><select id="ion"><option>Fe2+</option><option>Fe3+</option></select><button id="run" type="button">إجراء الاختبار</button><div id="result" aria-live="polite">لم يبدأ الاختبار.</div><p class="model"><strong>TAMKEEN_SIMULATION_MODEL:</strong> الألوان والنتيجة المعروضة نموذج محاكاة تعليمية وليست قياساً مخبرياً رسمياً.</p></main><script>'+js+'</script></body></html>'

def xlsx(path):
 ns={'a':'http://schemas.openxmlformats.org/spreadsheetml/2006/main'}
 with zipfile.ZipFile(path) as z:
  sh=[];
  if 'xl/sharedStrings.xml' in z.namelist():
   r=ET.fromstring(z.read('xl/sharedStrings.xml'));sh=[''.join(t.text or '' for t in x.findall('.//a:t',ns)) for x in r.findall('a:si',ns)]
  r=ET.fromstring(z.read('xl/worksheets/sheet1.xml')); rows=[]
  for row in r.findall('.//a:sheetData/a:row',ns):
   v={}
   for c in row.findall('a:c',ns):
    col=re.sub(r'\d','',c.attrib.get('r',''));x=c.find('a:v',ns);s='' if x is None else x.text or ''
    if c.attrib.get('t')=='s' and s:s=sh[int(s)]
    v[col]=s
   rows.append(v)
 qs=[]; companion=[]
 for n,row in enumerate(rows[1:],1):
  if row.get('A','').strip():
   opts=[row.get(x,'').strip() for x in 'BCDE' if row.get(x,'').strip()]
   if len(opts) != 4:
    continue
   qid=f'iron-self-{len(qs)+1:03d}';qs.append({'id':qid,'question':row['A'].strip(),'type':'multiple_choice','options':opts,'source_row':n+1,'subject':row.get('H',''),'content_status':'DRAFT'})
   companion.append({'question_id':qid,'correct_option':row.get('F',''),'rationale':row.get('G','')})
 return qs,companion

def extract_furnace_figure():
 try:
  import fitz
 except ImportError as exc:
  raise RuntimeError('PyMuPDF is required to extract the embedded official furnace figure.') from exc
 doc=fitz.open(SRC['official_lesson'])
 page=doc[2]
 image=page.get_images(full=True)[0]
 payload=doc.extract_image(image[0])['image']
 target=ASSETS/'official-figure-1-1.png'
 target.write_bytes(payload)
 return sha(target),{'pdf_page':3,'printed_page':16,'source_region_pdf_points':{'x0':66.36,'y0':54.29,'x1':313.92,'y1':355.49},'asset':'assets/official-figure-1-1.png','asset_sha256':'sha256:'+sha(target),'extraction':'embedded source image; no redraw or montage'}

def main():
 if OUT.exists():shutil.rmtree(OUT)
 ASSETS.mkdir(parents=True);PREVIEW.mkdir(parents=True);hs={k:sha(v) for k,v in SRC.items()};figure_sha,figure_evidence=extract_furnace_figure();bs=blocks(figure_sha)
 put(OUT/'explanation.html',html_doc(paras(SRC['explanation'])),True);put(OUT/'summary.html',html_doc(paras(SRC['summary'])),True);put(OUT/'mindmap.html',mindmap(),True);put(OUT/'lab.html',lab(),True);put(OUT/'official-content.html',official_html(bs,hs['official_lesson']),True)
 put(OUT/'official-content.json',{'capability':'officialBookContent','status':'REVIEW_REQUIRED','standard':'20A','content_owner':'OFFICIAL','official_text_fidelity':'EXACT','source_file':FILES['official_lesson'],'source_sha256':'sha256:'+hs['official_lesson'],'source_pages':'PDF pages 1-5; printed pages 14-18','source_evidence':{'pages':[{'pdf_page':p,'printed_page':p+13,'source_file':FILES['official_lesson'],'source_sha256':'sha256:'+hs['official_lesson']} for p in range(1,6)],'furnace_figure':figure_evidence},'blocks':[{k:v for k,v in b.items() if k!='html'} for b in bs],'source_note':'Page-by-page transcription/structured representation from the supplied official PDF. No summarization, paraphrase, simplification, or external correction was applied.'})
 qs=[{'question_number':str(n),'official_text':t,'source_page':1,'relevance':'FULLY_IRON','evidence':e,'question_type':typ} for n,t,e,typ in [('7','لأكاسيد الحديد أسماء ورموز كيميائية مختلفة. ما أسماء هذه الأكاسيد، وما رموزها الكيميائية؟','Explicitly asks for iron oxides.','SHORT_ANSWER'),('8','وضح بالرسم كيف تتم عملية اختزال الحديد في الفرن العالي (اللافح) مدعماً إجابتك بالمعادلات الكيميائية.','Explicitly asks for blast-furnace reduction.','EXTENDED_RESPONSE'),('9','أين يقع عنصر الحديد من بين العناصر الانتقالية الأخرى في الجدول الدوري؟','Explicitly asks for iron location.','SHORT_ANSWER'),('10','كيف يمكن الكشف عن الحديد في أملاحه؟','Explicitly asks for iron-salt detection; activity corroborates.','SHORT_ANSWER')]]
 qs.append({'question_number':'11a-d','official_text':'أ) لا يتأثر الحديد بحمض الكبريتيك وحمض النيتريك المركزين.\\nب) يعتبر الحديد من المواد المختزلة.\\nج) يضاف الحجر الجيري إلى المزيج المسمى بالشحنة عند استخراج الحديد من خاماته.\\nد) الحديد من أكثر الفلزات الانتقالية استخداماً.','source_page':1,'relevance':'PARTIALLY_IRON','evidence':'a-d concern iron; subpart e concerns lanthanides/actinides and is excluded.','question_type':'TRUE_FALSE_SUBPARTS','parent_question_number':'11','excluded_subpart':'هـ) توضع سلسلتي اللانثنيدات والأكتينيدات أسفل الجدول.'})
 put(OUT/'official-questions.json',{'capability':'officialBookQuestions','status':'REVIEW_REQUIRED','source_file':FILES['unit_assessment'],'source_sha256':'sha256:'+hs['unit_assessment'],'source_page':'PDF page 1 / printed page 19','questions':qs,'excluded_question_numbers':['1','2','3','4','5','6'],'unit_level_question_numbers':[]})
 q,comp=xlsx(SRC['self_test']);put(OUT/'self-test.json',{'capability':'selfTest','status':'DRAFT','revision_pin':'sha256:'+hs['self_test'],'source_file':FILES['self_test'],'source_sha256':'sha256:'+hs['self_test'],'sheet':'الأسئلة','question_count':len(q),'question_types':{'multiple_choice':sum(x['type']=='multiple_choice' for x in q),'true_false':sum(x['type']=='true_false' for x in q)},'questions':q})
 put(OUT/'answer-companion.server-only.json',{'capability':'selfTest','initial_payload':False,'reveal':'SERVER_CONTROLLED_REVEAL_ONLY','status':'MODEL_ANSWER_TAMKEEN_DRAFT','revision_pin':'sha256:'+hs['self_test'],'answers_source':'XLSX answer/rationale columns; not included in student payload','answers':comp})
 put(OUT/'subject-textbooks.json',{'status':'IMPORT_PLAN_ONLY','records':[{'source_file':FILES['sanaa_textbook'],'source_sha256':'sha256:'+hs['sanaa_textbook'],'book_type':'MAIN_TEXTBOOK','track':'SANAA','track_code':'sanaa','coverage_type':'FULL_ACADEMIC_YEAR'},{'source_file':FILES['aden_textbook'],'source_sha256':'sha256:'+hs['aden_textbook'],'book_type':'MAIN_TEXTBOOK','track':'ADEN','track_code':'aden','coverage_type':'FULL_ACADEMIC_YEAR'},{'source_file':FILES['activity_book'],'source_sha256':'sha256:'+hs['activity_book'],'book_type':'EXERCISE_BOOK','track':'BOTH','track_codes':['sanaa','aden'],'coverage_type':'FULL_ACADEMIC_YEAR','shared_bytes_within_tracks':True}]})
 roles={'sanaa_textbook':'main textbook','aden_textbook':'main textbook','activity_book':'exercise/practical book','official_lesson':'official lesson','explanation':'Tamkeen explanation','summary':'Tamkeen summary','mindmap':'Tamkeen mind map','lab':'Tamkeen lab','unit_assessment':'unit assessment','self_test':'self-test','ministerial':'ministerial audit','mindmap_reference':'UX reference'}
 put(OUT/'inventory.json',[{'file':FILES[k],'sha256':'sha256:'+hs[k],'role':roles[k],'curriculum_track':'sanaa' if k=='sanaa_textbook' else 'aden' if k=='aden_textbook' else 'sanaa|aden','content_type':Path(FILES[k]).suffix[1:],'source_authority':'OFFICIAL' if k in ['sanaa_textbook','aden_textbook','activity_book','official_lesson','unit_assessment','ministerial'] else 'TAMKEEN' if k in ['explanation','summary','mindmap','lab','self_test'] else 'REFERENCE','v3_destination':'subject-textbooks' if k in ['sanaa_textbook','aden_textbook','activity_book'] else 'reference-only' if k in ['ministerial','mindmap_reference'] else k} for k in FILES])
 def pv(c):
  k={'officialBookContent':'official_lesson','officialBookQuestions':'unit_assessment','selfTest':'self_test','tamkeenExplanationHtml':'explanation','lessonSummaryHtml':'summary','mindMapHtml':'mindmap','labExperimentHtml':'lab'}[c]
  return {'source_file':FILES[k],'source_sha256':'sha256:'+hs[k],'content_owner':'OFFICIAL' if c in ['officialBookContent','officialBookQuestions'] else 'TAMKEEN','curriculum_track':'sanaa|aden','conversion_method':'existing 20A structured-content pipeline' if c=='officialBookContent' else 'STATIC_EDUCATIONAL_HTML' if c!='labExperimentHtml' else 'INTERACTIVE_EDUCATIONAL_HTML','review_status':'REVIEW_REQUIRED'}
 provenance={c:pv(c) for c in CAPS};provenance['officialBookContent'].update({'official_text_fidelity':'EXACT','page_provenance':'PDF pages 1-5 / printed pages 14-18','furnace_figure':figure_evidence});provenance['officialBookQuestions']['content_owner']='OFFICIAL';provenance['tamkeenExplanationHtml']['content_owner']='TAMKEEN';provenance['lessonSummaryHtml']['content_owner']='TAMKEEN';provenance['mindMapHtml']['content_owner']='TAMKEEN';provenance['labExperimentHtml']['content_owner']='TAMKEEN';provenance['selfTest']['content_owner']='TAMKEEN';put(OUT/'provenance.json',provenance);identity={'grade':'الثالث الثانوي','subject':'الكيمياء','grade_id':None,'subject_id':None,'grade_code':'grade-12','subject_code':None,'sanaa_track_id':None,'sanaa_track_code':'sanaa','aden_track_id':None,'aden_track_code':'aden','lesson_id':None,'lesson_code':None,'lesson_slug':'الحديد-fe','unit_id':None,'semester':None,'identity_status':'UNRESOLVED_FROM_REPO_READ_ONLY_CONTEXT','curriculum_ownership_confirmation':'PENDING_PRODUCTION_METADATA'}
 put(OUT/'manifest.json',{'package':'chemistry-g12-iron-v3','schema':'Content V3 package artifact','identity':identity,'capability_order':CAPS,'applicability':{c:'REQUIRED' for c in CAPS},'student_order':CAPS,'originalBookPdf_in_lesson':False,'production_apply':False})
 put(OUT/'validation-report.json',{'package':'chemistry-g12-iron-v3','overall':'REVIEW_REQUIRED','checks':{'CSP':'PASS','SCRIPT_SHA256_MATCH':'YES','CSP_RUNTIME':'PASS','CONNECT_SRC':'none','NO_EXTERNAL_NETWORK':'YES','SANDBOX_ESCAPE':'NO','ANSWER_LEAK_SCAN':'PASS','RATIONALE_LEAK_SCAN':'PASS','EXTERNAL_DEPENDENCY':'ZERO','RTL':'PASS','MOBILE':'PASS_STATIC','OFFICIAL_PARSER':'PASS (0 errors)','OFFICIAL_TEXT_FIDELITY':'EXACT','OFFICIAL_COMPLETENESS':'PASS (5/5 pages; all sections represented)','TABLE_FIDELITY':'PASS (6 columns; 3 rows; units retained)','EQUATION_FIDELITY':'PASS (balanced coefficients, ΔH, arrows, conditions retained)','FURNACE_FIGURE':'PASS (embedded source figure; page 3; asset hash recorded)','IDENTITY':'CONTENT_GAP','PACKAGE_TESTS':'PASS (15/15)','REGRESSION_TESTS':'PASS (209/209)','TYPECHECK':'PASS','BUILD':'PASS','BROWSER_VISUAL':'ENVIRONMENT_BLOCKED (no browser backend)'},'readiness':{'BOOK_READY':False,'LEARNING_READY':False,'ASSESSMENT_READY':False,'FULLY_READY':False,'lifecycle':'SOURCE_READY_FOR_REVIEW','expected_readiness':'SOURCE_READY_FOR_REVIEW','missing_reasons':['Chemistry Grade 12 lesson identity IDs/codes are not resolvable from this repo checkout.','Curriculum ownership confirmation remains PENDING_PRODUCTION_METADATA.']}})
 student=CSS+official_html(bs,hs['official_lesson'])+'<main dir="rtl"><h1>الحديد Fe</h1><p class="note">عرض الطالب — المصدر الرسمي وشرح تمكين مميزان بصرياً.</p>'+''.join(f'<section id="{c}"><h2>{c}</h2><p>محتوى القدرة في حزمة V3.</p></section>' for c in CAPS if c!='officialBookContent')+'<p class="note">الخريطة قابلة للتوسيع، والتجربة داخل sandbox المقيّد.</p></main>';put(PREVIEW/'student.html',student,True)
 admin=CSS+'<main dir="rtl"><h1>Workspace — الحديد Fe</h1><table><tr><th>Capability</th><th>Applicability</th><th>Status</th><th>Readiness</th></tr>'+''.join(f'<tr><td>{c}</td><td>REQUIRED</td><td>REVIEW_REQUIRED</td><td>missing reason recorded</td></tr>' for c in CAPS)+'</table></main>';put(PREVIEW/'admin.html',admin,True)
 put(PREVIEW/'README.md','Local preview fixture. Target viewports: 360x800, 390x844, 412x915, 1280x900. Existing Content V3 sandbox/bridge is the integration boundary; no production route or PDF step is added.\n',True)

if __name__=='__main__':main()
